-- seed.sql — Catálogo de ejercicios globales (created_by IS NULL)
-- Generado por build_exercise_db.py desde 'base datos ejercicios(1).xlsx'.
-- NO editar a mano: re-generar con `py build_exercise_db.py`.

insert into public.exercises
  (name, primary_muscle_group, secondary_muscle_groups, equipment, movement_type, difficulty, instructions, image_url)
values
  ('Press de Banca Plano', 'Pecho', ARRAY['Triceps', 'Hombros (anterior)'], 'Barra', 'Empuje horizontal', 'Intermedio', 'Agarre a la anchura de los hombros, bajar la barra al pecho y empujar.', '/exercises/1.jpg'),
  ('Press de Banca Inclinado', 'Pecho', ARRAY['Hombros (anterior)', 'Triceps'], 'Barra', 'Empuje inclinado', 'Intermedio', 'Banco a 30-45, enfatiza la parte superior del pecho.', '/exercises/2.jpg'),
  ('Press de Banca Declinado', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Barra', 'Empuje declinado', 'Intermedio', 'Banco declinado, enfatiza la parte inferior del pecho.', NULL),
  ('Press de Banca Agarre Estrecho', 'Triceps', ARRAY['Pecho', 'Hombros'], 'Barra', 'Empuje estrecho', 'Intermedio', 'Agarre a la anchura de hombros, codos pegados al cuerpo.', '/exercises/4.jpg'),
  ('Press Guillotina (Neck Press)', 'Pecho', ARRAY['Triceps'], 'Barra', 'Empuje horizontal alto', 'Avanzado', 'Barra baja hacia el cuello/garganta, maximo estiramiento pectoral superior.', '/exercises/5.jpg'),
  ('Svend Press', 'Pecho', ARRAY['Hombros (anterior)'], 'Peso Corporal', 'Aislamiento de aduccion', 'Principiante', 'Plato presionado entre las manos frente al pecho, empujar hacia adelante manteniendo la presion.', '/exercises/6.jpg'),
  ('Press de Banca con Mancuernas', 'Pecho', ARRAY['Triceps', 'Hombros (anterior)'], 'Mancuernas', 'Empuje horizontal', 'Principiante', 'Mayor rango de movimiento que con barra.', '/exercises/7.jpg'),
  ('Press Inclinado con Mancuernas', 'Pecho', ARRAY['Hombros (anterior)', 'Triceps'], 'Mancuernas', 'Empuje inclinado', 'Principiante', 'Banco a 30-45.', '/exercises/8.jpg'),
  ('Press Declinado con Mancuernas', 'Pecho', ARRAY['Triceps'], 'Mancuernas', 'Empuje declinado', 'Principiante', 'Banco declinado, codos a 75 grados.', '/exercises/9.jpg'),
  ('Aperturas con Mancuernas Plano', 'Pecho', ARRAY['Hombros (anterior)'], 'Mancuernas', 'Aislamiento horizontal', 'Principiante', 'Brazos ligeramente flexionados, arco amplio.', '/exercises/10.jpg'),
  ('Aperturas Inclinadas con Mancuernas', 'Pecho', ARRAY['Hombros (anterior)'], 'Mancuernas', 'Aislamiento inclinado', 'Principiante', 'Banco a 30, arco controlado.', '/exercises/11.jpg'),
  ('Aperturas Declinadas con Mancuernas', 'Pecho', ARRAY['Hombros (anterior)'], 'Mancuernas', 'Aislamiento declinado', 'Principiante', 'Banco declinado, enfasis en pecho inferior.', '/exercises/12.jpg'),
  ('Pullover con Mancuerna', 'Pecho', ARRAY['Dorsal', 'Triceps'], 'Mancuernas', 'Aislamiento', 'Intermedio', 'Tumbado en banco, bajar la mancuerna por detras de la cabeza.', '/exercises/13.jpg'),
  ('Press de Banca con Mancuernas Agarre Neutro', 'Pecho', ARRAY['Triceps'], 'Mancuernas', 'Empuje horizontal neutro', 'Principiante', 'Palmas enfrentadas, menos estres en hombros.', '/exercises/14.jpg'),
  ('Press de Banca Una Mancuerna (Unilateral)', 'Pecho', ARRAY['Triceps', 'Core'], 'Mancuernas', 'Empuje horizontal unilateral', 'Intermedio', 'Un brazo a la vez, mayor demanda de estabilizacion.', '/exercises/15.jpg'),
  ('Press en Maquina Pecho Plano', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Maquina', 'Empuje horizontal', 'Principiante', 'Guiado, ideal para principiantes o fatiga.', '/exercises/16.jpg'),
  ('Press en Maquina Pecho Inclinado', 'Pecho', ARRAY['Hombros (anterior)', 'Triceps'], 'Maquina', 'Empuje inclinado', 'Principiante', 'Angulo fijo, enfasis pecho superior.', '/exercises/17.jpg'),
  ('Pec Deck (Aperturas en Maquina)', 'Pecho', ARRAY['Hombros (anterior)'], 'Maquina', 'Aislamiento horizontal', 'Principiante', 'Mantener tension constante, ideal para finalizacion.', '/exercises/18.jpg'),
  ('Hammer Strength Press Plano', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Maquina', 'Empuje horizontal articulado', 'Intermedio', 'Maquina de palanca, permite movimiento mas natural que guiado.', '/exercises/19.jpg'),
  ('Hammer Strength Press Inclinado', 'Pecho', ARRAY['Hombros (anterior)', 'Triceps'], 'Maquina', 'Empuje inclinado articulado', 'Intermedio', 'Palanca inclinada, pecho superior.', '/exercises/20.jpg'),
  ('Press en Maquina Smith Plano', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Maquina Smith', 'Empuje horizontal guiado', 'Principiante', 'Movimiento guiado en plano horizontal.', '/exercises/21.jpg'),
  ('Press en Maquina Smith Inclinado', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Maquina Smith', 'Empuje inclinado guiado', 'Principiante', 'Movimiento guiado en plano inclinado.', '/exercises/22.jpg'),
  ('Cruce de Poleas Alto a Bajo', 'Pecho', ARRAY['Hombros (anterior)'], 'Cable', 'Aislamiento cruzado', 'Principiante', 'Poleas altas, cruzar hacia abajo y adentro.', '/exercises/23.jpg'),
  ('Cruce de Poleas Bajo a Alto', 'Pecho', ARRAY['Hombros (anterior)'], 'Cable', 'Aislamiento cruzado', 'Principiante', 'Poleas bajas, cruzar hacia arriba.', '/exercises/24.jpg'),
  ('Cruce de Poleas Neutro', 'Pecho', ARRAY['Hombros (anterior)'], 'Cable', 'Aislamiento cruzado', 'Principiante', 'Poleas a altura media.', '/exercises/25.jpg'),
  ('Press con Cable Plano', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Cable', 'Empuje horizontal', 'Intermedio', 'Tension constante a diferencia de la barra.', '/exercises/26.jpg'),
  ('Press con Cable Inclinado', 'Pecho', ARRAY['Hombros (anterior)', 'Triceps'], 'Cable', 'Empuje inclinado', 'Intermedio', 'Polea baja, enfasis pecho superior.', '/exercises/27.jpg'),
  ('Apertura Unilateral en Cable', 'Pecho', ARRAY['Hombros (anterior)'], 'Cable', 'Aislamiento unilateral', 'Intermedio', 'Un brazo a la vez, mayor rango y contraccion.', '/exercises/28.jpg'),
  ('Flexiones (Push-ups)', 'Pecho', ARRAY['Triceps', 'Hombros', 'Core'], 'Peso Corporal', 'Empuje horizontal', 'Principiante', 'Manos a anchura de hombros, cuerpo recto.', '/exercises/29.jpg'),
  ('Flexiones Inclinadas (Pies Elevados)', 'Pecho', ARRAY['Pecho Superior', 'Triceps'], 'Peso Corporal', 'Empuje declinado', 'Intermedio', 'Pies elevados, mayor enfasis pecho superior.', '/exercises/30.jpg'),
  ('Flexiones Declinadas (Manos Elevadas)', 'Pecho', ARRAY['Pecho Inferior', 'Triceps'], 'Peso Corporal', 'Empuje inclinado', 'Principiante', 'Manos sobre superficie elevada, pecho inferior.', '/exercises/31.jpg'),
  ('Flexiones Explosivas (Clap Push-ups)', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Peso Corporal', 'Empuje horizontal explosivo', 'Avanzado', 'Empujar con fuerza para despegar las manos y aplaudir.', '/exercises/32.jpg'),
  ('Fondos en Paralelas (Pecho)', 'Pecho', ARRAY['Triceps', 'Hombros'], 'Peso Corporal', 'Empuje vertical declinado', 'Intermedio', 'Inclinar el torso hacia adelante para mayor enfasis en pecho.', '/exercises/33.jpg'),
  ('Flexiones Arqueras (Archer Push-ups)', 'Pecho', ARRAY['Triceps'], 'Peso Corporal', 'Empuje unilateral', 'Avanzado', 'Extender un brazo lateralmente mientras el otro hace la flexion.', '/exercises/34.jpg'),
  ('Flexiones con Manos Juntas', 'Triceps', ARRAY['Pecho'], 'Peso Corporal', 'Empuje estrecho', 'Intermedio', 'Mayor activacion del triceps lateral.', '/exercises/35.jpg'),
  ('Push-up en Anillas', 'Pecho', ARRAY['Triceps', 'Core', 'Hombros'], 'Peso Corporal', 'Empuje horizontal inestable', 'Avanzado', 'Manos en anillas, requiere gran estabilizacion escapular.', '/exercises/36.jpg'),
  ('Peso Muerto Convencional', 'Espalda Baja', ARRAY['Gluteos', 'Isquiotibiales', 'Trapecios', 'Cuadriceps'], 'Barra', 'Bisagra de cadera', 'Avanzado', 'Barra sobre el mediepie, espalda neutra, empujar el suelo al tirar.', '/exercises/37.jpg'),
  ('Peso Muerto Sumo', 'Gluteos', ARRAY['Isquiotibiales', 'Aductores', 'Cuadriceps', 'Espalda Baja'], 'Barra', 'Bisagra de cadera amplia', 'Avanzado', 'Pies muy abiertos, puntas hacia afuera, agarre interior, torso mas erguido.', '/exercises/38.jpg'),
  ('Peso Muerto Rumano', 'Isquiotibiales', ARRAY['Gluteos', 'Espalda Baja'], 'Barra', 'Bisagra de cadera', 'Intermedio', 'Rodillas ligeramente flexionadas, barra baja por las piernas.', '/exercises/39.jpg'),
  ('Peso Muerto con Barra Trap (Hexagonal)', 'Espalda Baja', ARRAY['Gluteos', 'Isquiotibiales', 'Cuadriceps'], 'Barra Hexagonal', 'Bisagra de cadera', 'Intermedio', 'Barra hexagonal, agarre neutro, postura intermedia entre convencional y sentadilla.', '/exercises/40.jpg'),
  ('Peso Muerto Piernas Rigidas (SLDL)', 'Isquiotibiales', ARRAY['Gluteos', 'Espalda Baja'], 'Barra', 'Bisagra de cadera', 'Intermedio', 'Rodillas casi bloqueadas, maximo estiramiento de isquiotibiales.', '/exercises/41.jpg'),
  ('Peso Muerto Sumo con Mancuernas', 'Gluteos', ARRAY['Isquiotibiales', 'Aductores'], 'Mancuernas', 'Bisagra de cadera amplia', 'Principiante', 'Postura sumo, mancuernas frente al cuerpo.', '/exercises/42.jpg'),
  ('Peso Muerto con Deficit', 'Espalda Baja', ARRAY['Gluteos', 'Isquiotibiales'], 'Barra', 'Bisagra de cadera desde elevacion', 'Avanzado', 'De pie sobre una plataforma elevada, mayor rango de movimiento.', '/exercises/43.jpg'),
  ('Peso Muerto a Una Pierna con Barra', 'Isquiotibiales', ARRAY['Gluteos', 'Core'], 'Barra', 'Bisagra de cadera unilateral', 'Avanzado', 'Mayor demanda de equilibrio y estabilizacion.', '/exercises/44.jpg'),
  ('Buenos Dias (Good Morning)', 'Espalda Baja', ARRAY['Isquiotibiales', 'Gluteos'], 'Barra', 'Bisagra de cadera', 'Avanzado', 'Barra en trapecios, inclinarse hasta la horizontal manteniendo espalda neutra.', '/exercises/45.jpg'),
  ('Hiperextension con Barra', 'Espalda Baja', ARRAY['Gluteos', 'Isquiotibiales'], 'Barra', 'Extension de cadera/columna', 'Intermedio', 'En banco romano, sostener una barra frente al pecho.', '/exercises/46.jpg'),
  ('Remo con Barra Prono (Pendlay)', 'Espalda Alta', ARRAY['Biceps', 'Romboides', 'Trapecios'], 'Barra', 'Traccion horizontal', 'Intermedio', 'Torso paralelo al suelo, tirar la barra hacia el abdomen bajo.', '/exercises/47.jpg'),
  ('Remo con Barra Supino', 'Espalda Alta', ARRAY['Biceps'], 'Barra', 'Traccion horizontal supina', 'Intermedio', 'Agarre supino, mayor activacion del dorsal.', '/exercises/48.jpg'),
  ('Remo con Barra Agarre Estrecho', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Barra', 'Traccion horizontal estrecha', 'Intermedio', 'Manos juntas, mayor enfasis en romboides.', '/exercises/49.jpg'),
  ('Remo al Menton con Barra', 'Trapecios', ARRAY['Hombros (lateral)', 'Biceps'], 'Barra', 'Traccion vertical', 'Intermedio', 'Agarre estrecho, tirar la barra hacia el menton.', '/exercises/50.jpg'),
  ('Remo con Barra en T (T-Bar Row)', 'Espalda Alta', ARRAY['Biceps', 'Romboides', 'Trapecios'], 'Barra', 'Traccion horizontal', 'Intermedio', 'Un extremo de la barra anclado, tirar del otro extremo con mangos.', '/exercises/51.jpg'),
  ('Remo Chest Supported en T-Bar', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Barra', 'Traccion horizontal apoyada', 'Intermedio', 'Pecho apoyado en pad inclinado, elimina el uso de la espalda baja.', '/exercises/52.jpg'),
  ('Seal Row', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Barra', 'Traccion horizontal tumbado', 'Avanzado', 'Tumbado boca abajo sobre un banco alto, remo colgando libremente.', '/exercises/53.jpg'),
  ('Jalon al Pecho con barra', 'Dorsal', ARRAY['Biceps', 'Romboides'], 'Maquina', 'Traccion vertical amplia', 'Principiante', 'Barra larga, agarre prono, tirar hacia la clavicula.', '/exercises/54.jpg'),
  ('Jalon Tras Nuca', 'Dorsal', ARRAY['Biceps', 'Romboides'], 'Maquina', 'Traccion vertical posterior', 'Intermedio', 'Barra detras de la cabeza, requiere buena movilidad cervical.', '/exercises/55.jpg'),
  ('Jalon Agarre Supino', 'Dorsal', ARRAY['Biceps'], 'Maquina', 'Traccion vertical supina', 'Principiante', 'Palmas mirando hacia vos, mayor activacion de biceps.', '/exercises/56.jpg'),
  ('Remo en Maquina Sentado (Polea)', 'Espalda Alta', ARRAY['Biceps', 'Romboides', 'Trapecios'], 'Maquina', 'Traccion horizontal sentado', 'Principiante', 'Pies en los pedales, tirar con mangos hacia el abdomen.', '/exercises/57.jpg'),
  ('Remo Hammer Strength Un Brazo', 'Espalda Alta', ARRAY['Biceps'], 'Maquina', 'Traccion horizontal unilateral', 'Principiante', 'Palanca articulada, un brazo a la vez.', '/exercises/58.jpg'),
  ('Remo Hammer Strength Bilateral', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Maquina', 'Traccion horizontal bilateral', 'Principiante', 'Ambos brazos simultaneamente.', '/exercises/59.jpg'),
  ('Pullover en Maquina (Nautilus)', 'Dorsal', ARRAY['Triceps largo', 'Pecho'], 'Maquina', 'Tiracion vertical/anterior', 'Intermedio', 'Codos sobre el pad, llevar los brazos de arriba hacia adelante y abajo.', '/exercises/60.jpg'),
  ('Jalon Unilateral (Cable)', 'Dorsal', ARRAY['Biceps'], 'Cable', 'Traccion vertical unilateral', 'Intermedio', 'Un brazo a la vez, mayor rango y contraccion.', '/exercises/61.jpg'),
  ('Remo con Cable Sentado (Mangos V)', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Cable', 'Traccion horizontal', 'Principiante', 'Mangos V, tirar con codos pegados al cuerpo.', '/exercises/62.jpg'),
  ('Remo con Cable Agarre Amplio', 'Espalda Alta', ARRAY['Romboides', 'Trapecios'], 'Cable', 'Traccion horizontal amplia', 'Intermedio', 'Barra larga, codos hacia afuera, mayor trabajo de romboides.', '/exercises/63.jpg'),
  ('Remo Unilateral con Cable', 'Espalda Alta', ARRAY['Biceps'], 'Cable', 'Traccion horizontal unilateral', 'Intermedio', 'Un brazo, mayor rango de rotacion escapular.', '/exercises/64.jpg'),
  ('Face Pull', 'Trapecios', ARRAY['Hombros (posterior)', 'Manguito Rotador'], 'Cable', 'Traccion diagonal', 'Principiante', 'Polea alta, tirar hacia la cara separando las manos.', '/exercises/65.jpg'),
  ('Pullover con Cable', 'Dorsal', ARRAY['Triceps largo', 'Pecho'], 'Cable', 'Tiracion vertical/anterior', 'Intermedio', 'Polea alta, tirar hacia los muslos manteniendo brazos semi-extendidos.', '/exercises/66.jpg'),
  ('Remo de Pie con Cable (Polea Baja)', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Cable', 'Traccion horizontal de pie', 'Principiante', 'Polea baja, tirar hacia el abdomen de pie.', '/exercises/67.jpg'),
  ('Straight Arm Pulldown', 'Dorsal', ARRAY['Triceps largo'], 'Cable', 'Tiracion vertical', 'Intermedio', 'Brazos casi extendidos, tirar la barra/cuerda de arriba hacia los muslos.', '/exercises/68.jpg'),
  ('Dominadas Agarre Prono (Pull-ups)', 'Dorsal', ARRAY['Biceps', 'Romboides'], 'Peso Corporal', 'Traccion vertical', 'Avanzado', 'Agarre prono mas ancho que los hombros, subir hasta la barbilla.', '/exercises/69.jpg'),
  ('Dominadas Agarre Supino (Chin-ups)', 'Dorsal', ARRAY['Biceps'], 'Peso Corporal', 'Traccion vertical supina', 'Intermedio', 'Agarre supino, mayor activacion de biceps.', '/exercises/70.jpg'),
  ('Dominadas Agarre Neutro', 'Dorsal', ARRAY['Biceps', 'Braquial'], 'Peso Corporal', 'Traccion vertical neutra', 'Intermedio', 'Manos enfrentadas, posicion intermedia.', '/exercises/71.jpg'),
  ('Dominadas Agarre Estrecho', 'Dorsal', ARRAY['Biceps'], 'Peso Corporal', 'Traccion vertical estrecha', 'Avanzado', 'Manos juntas, mayor enfasis en la parte interna del dorsal.', '/exercises/72.jpg'),
  ('Dominadas con Lastre', 'Dorsal', ARRAY['Biceps', 'Romboides'], 'Peso Corporal', 'Traccion vertical con carga extra', 'Avanzado', 'Cinto con disco o chaleco lastrado.', '/exercises/73.jpg'),
  ('Muscle Up', 'Dorsal', ARRAY['Triceps', 'Hombros', 'Core'], 'Peso Corporal', 'Traccion + empuje vertical', 'Avanzado', 'Subir por encima de la barra llevando el pecho.', '/exercises/74.jpg'),
  ('Remo Invertido en Barra Baja', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'Peso Corporal', 'Traccion horizontal', 'Principiante', 'Cuerpo inclinado bajo la barra, tirar el pecho hacia la barra.', '/exercises/75.jpg'),
  ('Remo Invertido TRX', 'Espalda Alta', ARRAY['Biceps', 'Romboides'], 'TRX / Suspension', 'Traccion horizontal', 'Principiante', 'Mayor inclinacion = mayor dificultad.', '/exercises/76.jpg'),
  ('Dead Hang', 'Espalda Alta', ARRAY['Hombros', 'Antebrazo'], 'Peso Corporal', 'Descompresion/grip isometrico', 'Principiante', 'Colgar de la barra, descomprimir la columna, trabajar el agarre.', '/exercises/77.jpg'),
  ('Active Hang (Escapular Pull-up)', 'Dorsal', ARRAY['Trapecios'], 'Peso Corporal', 'Depresion escapular', 'Intermedio', 'Sin doblar los codos, retraer y deprimir las escapulas desde el hang.', '/exercises/78.jpg'),
  ('Press Militar con Barra De Pie', 'Hombros', ARRAY['Triceps', 'Trapecios', 'Core'], 'Barra', 'Empuje vertical', 'Intermedio', 'Agarre a la anchura de hombros, press sobre la cabeza.', '/exercises/79.jpg'),
  ('Press Militar con Barra Sentado', 'Hombros', ARRAY['Triceps', 'Trapecios'], 'Barra', 'Empuje vertical', 'Principiante', 'Version sentada, mas estable.', '/exercises/80.jpg'),
  ('Push Press con Barra', 'Hombros', ARRAY['Triceps', 'Cuadriceps', 'Core'], 'Barra', 'Empuje vertical explosivo', 'Intermedio', 'Ligero impulso de piernas para dar inercia a la barra.', '/exercises/81.jpg'),
  ('Push Jerk', 'Hombros', ARRAY['Triceps', 'Cuadriceps', 'Core'], 'Barra', 'Empuje vertical olimpico', 'Avanzado', 'Impulso de piernas, caer bajo la barra con brazos extendidos.', '/exercises/82.jpg'),
  ('Press con Barra Landmine (Un Brazo)', 'Hombros', ARRAY['Triceps', 'Core'], 'Barra', 'Empuje semi-vertical', 'Intermedio', 'Un extremo de la barra anclado en esquina, press diagonal.', '/exercises/83.jpg'),
  ('Remo al Menton con Mancuernas', 'Trapecios', ARRAY['Hombros (lateral)', 'Biceps'], 'Mancuernas', 'Traccion vertical', 'Intermedio', 'Mancuernas frente al cuerpo, codos por encima de las munecas.', '/exercises/84.jpg'),
  ('Press de Hombros con Mancuernas Sentado', 'Hombros', ARRAY['Triceps'], 'Mancuernas', 'Empuje vertical', 'Principiante', 'Banco con respaldo, mas estable.', '/exercises/85.jpg'),
  ('Press de Hombros con Mancuernas De Pie', 'Hombros', ARRAY['Triceps', 'Core'], 'Mancuernas', 'Empuje vertical de pie', 'Intermedio', 'Mayor demanda de estabilizacion del core.', '/exercises/86.jpg'),
  ('Elevaciones Laterales', 'Hombros (lateral)', ARRAY['Trapecios'], 'Mancuernas', 'Aislamiento lateral', 'Principiante', 'Brazos ligeramente flexionados, elevar hasta la altura del hombro.', '/exercises/87.jpg'),
  ('Elevaciones Laterales Inclinado', 'Hombros (lateral)', ARRAY['Trapecios'], 'Mancuernas', 'Aislamiento lateral inclinado', 'Intermedio', 'Cuerpo inclinado lateralmente, mayor rango efectivo.', '/exercises/88.jpg'),
  ('Elevaciones Frontales Alternadas', 'Hombros (anterior)', ARRAY['Pecho Superior'], 'Mancuernas', 'Aislamiento frontal', 'Principiante', 'Alternar brazos, elevar al frente hasta la horizontal.', '/exercises/89.jpg'),
  ('Elevaciones Frontales Simultaneas', 'Hombros (anterior)', ARRAY['Pecho Superior'], 'Mancuernas', 'Aislamiento frontal bilateral', 'Principiante', 'Ambos brazos a la vez.', '/exercises/90.jpg'),
  ('Pajaro / Elevaciones Posteriores', 'Hombros (posterior)', ARRAY['Romboides', 'Trapecios'], 'Mancuernas', 'Aislamiento posterior', 'Principiante', 'Inclinado hacia adelante, abrir los brazos como alas.', '/exercises/91.jpg'),
  ('Press Arnold', 'Hombros', ARRAY['Triceps', 'Pecho'], 'Mancuernas', 'Empuje vertical con rotacion', 'Intermedio', 'Palmas hacia vos al inicio, rotar y extender sobre la cabeza.', '/exercises/92.jpg'),
  ('Press de Hombros en Maquina', 'Hombros', ARRAY['Triceps'], 'Maquina', 'Empuje vertical guiado', 'Principiante', 'Movimiento guiado, ideal para aprender.', '/exercises/93.jpg'),
  ('Elevaciones Laterales en Maquina', 'Hombros (lateral)', ARRAY['Trapecios'], 'Maquina', 'Aislamiento lateral guiado', 'Principiante', 'Tension constante a lo largo del rango.', '/exercises/94.jpg'),
  ('Reverse Pec Deck', 'Hombros (posterior)', ARRAY['Romboides'], 'Maquina', 'Aislamiento posterior', 'Principiante', 'Codos casi extendidos, abrir hacia atras.', '/exercises/95.jpg'),
  ('Maquina de Hombros Hammer Strength', 'Hombros', ARRAY['Triceps'], 'Maquina', 'Empuje vertical articulado', 'Principiante', 'Palanca articulada, movimiento mas natural.', '/exercises/96.jpg'),
  ('Elevaciones Laterales con Cable', 'Hombros (lateral)', ARRAY['Trapecios'], 'Cable', 'Aislamiento lateral', 'Principiante', 'Tension constante a diferencia de la mancuerna.', '/exercises/97.jpg'),
  ('Elevaciones Laterales Unilateral Cable', 'Hombros (lateral)', ARRAY['Trapecios'], 'Cable', 'Aislamiento lateral unilateral', 'Principiante', 'Polea baja, un brazo, tension constante.', '/exercises/98.jpg'),
  ('Elevaciones Frontales con Cable', 'Hombros (anterior)', ARRAY['Pecho Superior'], 'Cable', 'Aislamiento frontal', 'Principiante', 'Polea baja, elevar hacia el frente.', '/exercises/99.jpg'),
  ('Elevaciones Posteriores con Cable', 'Hombros (posterior)', ARRAY['Romboides'], 'Cable', 'Aislamiento posterior', 'Principiante', 'Polea alta, cruzando el cuerpo hacia abajo.', '/exercises/100.jpg'),
  ('Pike Push-up', 'Hombros', ARRAY['Triceps'], 'Peso Corporal', 'Empuje vertical', 'Intermedio', 'Caderas elevadas, cuerpo en V invertida, bajar la cabeza al suelo.', '/exercises/101.jpg'),
  ('Curl de Biceps con Barra', 'Biceps', ARRAY['Braquial', 'Braquiorradial'], 'Barra', 'Flexion de codo', 'Principiante', 'Codos fijos a los costados, curl completo.', '/exercises/102.jpg'),
  ('Curl de Biceps con Barra EZ', 'Biceps', ARRAY['Braquial', 'Braquiorradial'], 'Barra', 'Flexion de codo', 'Principiante', 'Agarre semisupino, menor estres en las munecas.', '/exercises/103.jpg'),
  ('Curl con Barra EZ Agarre Invertido', 'Braquiorradial', ARRAY['Biceps', 'Extensores del Antebrazo'], 'Barra', 'Flexion de codo prono', 'Principiante', 'Agarre prono, enfasis en braquiorradial.', '/exercises/104.jpg'),
  ('Curl de Biceps en Banco Scott con Barra EZ', 'Biceps', ARRAY['Braquial'], 'Barra', 'Flexion de codo apoyada', 'Principiante', 'Brazo apoyado en el pad inclinado, elimina el balanceo.', '/exercises/105.jpg'),
  ('Curl Alternado con Mancuernas', 'Biceps', ARRAY['Braquial'], 'Mancuernas', 'Flexion de codo unilateral', 'Principiante', 'Un brazo a la vez, supinar al subir.', '/exercises/106.jpg'),
  ('Curl Simultaneo con Mancuernas', 'Biceps', ARRAY['Braquial'], 'Mancuernas', 'Flexion de codo bilateral', 'Principiante', 'Ambos brazos a la vez.', '/exercises/107.jpg'),
  ('Curl Martillo', 'Braquiorradial', ARRAY['Biceps', 'Braquial'], 'Mancuernas', 'Flexion de codo neutral', 'Principiante', 'Agarre neutro, pulgares arriba.', '/exercises/108.jpg'),
  ('Curl Martillo Cruzado', 'Braquiorradial', ARRAY['Biceps', 'Braquial'], 'Mancuernas', 'Flexion de codo cruzada', 'Principiante', 'Elevar la mancuerna cruzando frente al pecho.', '/exercises/109.jpg'),
  ('Curl Concentrado', 'Biceps', ARRAY['Braquial'], 'Mancuernas', 'Flexion de codo aislada', 'Principiante', 'Codo apoyado en cara interna del muslo, maximo aislamiento.', '/exercises/110.jpg'),
  ('Curl en Banco Scott con Mancuernas', 'Biceps', ARRAY['Braquial'], 'Mancuernas', 'Flexion de codo apoyada', 'Principiante', 'Brazo apoyado en pad inclinado.', '/exercises/111.jpg'),
  ('Curl Spider', 'Biceps', ARRAY['Braquial'], 'Mancuernas', 'Flexion de codo inclinada', 'Intermedio', 'Pecho apoyado en banco inclinado, codos apuntando al suelo.', '/exercises/112.jpg'),
  ('Curl Inclinado Stretch', 'Biceps', ARRAY['Braquial'], 'Mancuernas', 'Flexion de codo elongada', 'Intermedio', 'Banco inclinado, maximo estiramiento del biceps.', '/exercises/113.jpg'),
  ('Curl de Muñeca Supino con Mancuerna', 'Flexores del Antebrazo', ARRAY['Biceps'], 'Mancuernas', 'Flexion de muneca', 'Principiante', 'Antebrazo apoyado, solo mueve la muneca.', '/exercises/114.jpg'),
  ('Curl de Biceps en Maquina Sentado', 'Biceps', ARRAY['Braquial'], 'Maquina', 'Flexion de codo guiada', 'Principiante', 'Movimiento guiado, tension constante.', '/exercises/115.jpg'),
  ('Curl de Biceps en Maquina de Predicador', 'Biceps', ARRAY['Braquial'], 'Maquina', 'Flexion de codo apoyada guiada', 'Principiante', 'Brazo sobre pad inclinado, movimiento guiado.', '/exercises/116.jpg'),
  ('Curl de Biceps en Cable Polea Baja', 'Biceps', ARRAY['Braquial'], 'Cable', 'Flexion de codo', 'Principiante', 'Tension constante en todo el rango.', '/exercises/117.jpg'),
  ('Curl Unilateral en Cable', 'Biceps', ARRAY['Braquial'], 'Cable', 'Flexion de codo unilateral', 'Principiante', 'Un brazo, maximo rango.', '/exercises/118.jpg'),
  ('Curl de Biceps Polea Alta (Supino)', 'Biceps', ARRAY['Braquial'], 'Cable', 'Flexion de codo en abduccion', 'Intermedio', 'Brazos abiertos a altura del hombro, doblar los codos.', '/exercises/119.jpg'),
  ('Press Frances con Barra EZ (Skullcrusher)', 'Triceps', ARRAY[]::text[], 'Barra', 'Extension de codo acostado', 'Intermedio', 'Barra a la frente doblando solo los codos.', '/exercises/120.jpg'),
  ('Press Frances Inclinado con Barra EZ', 'Triceps', ARRAY[]::text[], 'Barra', 'Extension de codo inclinada', 'Intermedio', 'Banco inclinado, mayor rango de movimiento.', '/exercises/121.jpg'),
  ('JM Press', 'Triceps', ARRAY['Pecho'], 'Barra', 'Hibrido press-skullcrusher', 'Avanzado', 'Hibrido entre press estrecho y press frances, muy eficiente para triceps.', '/exercises/122.jpg'),
  ('Press Frances con Mancuernas', 'Triceps', ARRAY[]::text[], 'Mancuernas', 'Extension de codo acostado', 'Principiante', 'Mancuernas bajan a los costados de la cabeza.', '/exercises/123.jpg'),
  ('Extension de Triceps Sobre la Cabeza', 'Triceps', ARRAY[]::text[], 'Mancuernas', 'Extension de codo sobre cabeza', 'Principiante', 'Mancuerna detras de la cabeza, extender los codos.', '/exercises/124.jpg'),
  ('Extension de Triceps Sobre Cabeza Bilateral', 'Triceps', ARRAY[]::text[], 'Mancuernas', 'Extension de codo sobre cabeza bilateral', 'Principiante', 'Una mancuerna sostenida con ambas manos detras de la cabeza.', '/exercises/125.jpg'),
  ('Patada de Triceps (Kickback)', 'Triceps', ARRAY[]::text[], 'Mancuernas', 'Extension de codo', 'Principiante', 'Inclinado, codo fijo, extender el brazo hacia atras.', '/exercises/126.jpg'),
  ('Pushdown de Triceps con Barra', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo', 'Principiante', 'Polea alta, codos fijos a los costados.', '/exercises/127.jpg'),
  ('Pushdown de Triceps con Cuerda', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo con rotacion', 'Principiante', 'Al final separar la cuerda hacia afuera.', '/exercises/128.jpg'),
  ('Pushdown de Triceps con Barra V', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo', 'Principiante', 'Barra V, agarre comodo para las munecas.', '/exercises/129.jpg'),
  ('Pushdown Unilateral con Cable', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo unilateral', 'Principiante', 'Un brazo a la vez, mayor rango.', '/exercises/130.jpg'),
  ('Extension de Triceps Sobre Cabeza (Cable)', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo sobre cabeza', 'Principiante', 'Polea alta, manos detras de la cabeza.', '/exercises/131.jpg'),
  ('Extension de Triceps Sobre Cabeza con Cuerda', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo sobre cabeza', 'Principiante', 'Polea alta, cuerda, mayor rango de separacion.', '/exercises/132.jpg'),
  ('Press Frances en Cable', 'Triceps', ARRAY[]::text[], 'Cable', 'Extension de codo acostado', 'Intermedio', 'Tumbado frente a la polea baja, skullcrusher con cable.', '/exercises/133.jpg'),
  ('Extension Triceps en Maquina', 'Triceps', ARRAY[]::text[], 'Maquina', 'Extension de codo guiada', 'Principiante', 'Tension constante, movimiento guiado.', '/exercises/134.jpg'),
  ('Dips en Maquina Asistida', 'Triceps', ARRAY['Pecho', 'Hombros'], 'Maquina', 'Empuje vertical asistido', 'Principiante', 'Maquina contrarresta parte del peso corporal.', '/exercises/135.jpg'),
  ('Fondos en Paralelas (Triceps)', 'Triceps', ARRAY['Pecho', 'Hombros'], 'Peso Corporal', 'Empuje vertical', 'Intermedio', 'Cuerpo erguido, codos pegados.', '/exercises/136.jpg'),
  ('Fondos en Banco (Bench Dips)', 'Triceps', ARRAY['Pecho'], 'Peso Corporal', 'Empuje decline', 'Principiante', 'Manos en banco detras, pies en suelo o elevados.', '/exercises/137.jpg'),
  ('Fondos en Banco Pies Elevados', 'Triceps', ARRAY['Pecho'], 'Peso Corporal', 'Empuje decline avanzado', 'Intermedio', 'Pies sobre otro banco, mayor carga.', '/exercises/138.jpg'),
  ('Diamond Push-up', 'Triceps', ARRAY['Pecho'], 'Peso Corporal', 'Empuje estrecho', 'Intermedio', 'Manos en diamante bajo el pecho.', '/exercises/139.jpg'),
  ('Sentadilla con Barra Alta (High Bar)', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales', 'Core'], 'Barra', 'Sentadilla', 'Intermedio', 'Barra en trapecios superior, torso mas erguido, mayor profundidad.', '/exercises/140.jpg'),
  ('Sentadilla con Barra Baja (Low Bar)', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales', 'Espalda Baja'], 'Barra', 'Sentadilla', 'Avanzado', 'Barra en trapecios medios, mayor inclinacion del torso.', '/exercises/141.jpg'),
  ('Sentadilla Frontal', 'Cuadriceps', ARRAY['Gluteos', 'Core'], 'Barra', 'Sentadilla', 'Avanzado', 'Barra en hombros delanteros, torso muy erguido.', '/exercises/142.jpg'),
  ('Sentadilla de Zercher', 'Cuadriceps', ARRAY['Gluteos', 'Core', 'Biceps'], 'Barra', 'Sentadilla', 'Avanzado', 'Barra en el pliegue de los codos, postura muy erguida.', '/exercises/143.jpg'),
  ('Sentadilla Overhead (OHS)', 'Cuadriceps', ARRAY['Core', 'Hombros', 'Gluteos'], 'Barra', 'Sentadilla con barra sobre cabeza', 'Avanzado', 'Requiere gran movilidad y estabilidad general.', '/exercises/144.jpg'),
  ('Sentadilla Sumo con Barra', 'Gluteos', ARRAY['Cuadriceps', 'Aductores'], 'Barra', 'Sentadilla amplia', 'Intermedio', 'Pies muy abiertos, puntas hacia afuera.', '/exercises/145.jpg'),
  ('Zancadas con Barra Al Frente', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Barra', 'Zancada hacia adelante', 'Intermedio', 'Un paso al frente, doblar ambas rodillas a 90.', '/exercises/146.jpg'),
  ('Zancadas con Barra Al Atras', 'Cuadriceps', ARRAY['Gluteos'], 'Barra', 'Zancada hacia atras', 'Intermedio', 'Paso hacia atras, mayor control de rodilla.', '/exercises/147.jpg'),
  ('Zancadas Caminando con Barra', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Barra', 'Zancada caminando', 'Intermedio', 'Avanzar con pasos alternos.', '/exercises/148.jpg'),
  ('Sentadilla Goblet con Mancuerna', 'Cuadriceps', ARRAY['Gluteos', 'Core'], 'Mancuernas', 'Sentadilla', 'Principiante', 'Mancuerna frente al pecho, torso erguido.', '/exercises/149.jpg'),
  ('Zancadas con Mancuernas Al Frente', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Mancuernas', 'Zancada hacia adelante', 'Principiante', 'Paso al frente, rodillas a 90.', '/exercises/150.jpg'),
  ('Zancadas Inversas con Mancuernas', 'Cuadriceps', ARRAY['Gluteos'], 'Mancuernas', 'Zancada hacia atras', 'Principiante', 'Paso hacia atras, mayor control de rodilla.', '/exercises/151.jpg'),
  ('Zancadas Laterales con Mancuernas', 'Gluteos', ARRAY['Cuadriceps', 'Aductores'], 'Mancuernas', 'Zancada lateral', 'Intermedio', 'Paso lateral, doblar la rodilla que carga el peso.', '/exercises/152.jpg'),
  ('Zancadas Caminando con Mancuernas', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Mancuernas', 'Zancada caminando', 'Principiante', 'Avanzar con pasos alternos.', '/exercises/153.jpg'),
  ('Step-Up con Mancuernas', 'Cuadriceps', ARRAY['Gluteos'], 'Mancuernas', 'Unilateral cadera/rodilla', 'Principiante', 'Subir a un banco con una pierna a la vez.', '/exercises/154.jpg'),
  ('Extension de Cuadriceps en Maquina', 'Cuadriceps', ARRAY[]::text[], 'Maquina', 'Extension de rodilla', 'Principiante', 'Sentado, extender las rodillas.', '/exercises/155.jpg'),
  ('Extension Unilateral en Maquina', 'Cuadriceps', ARRAY[]::text[], 'Maquina', 'Extension de rodilla unilateral', 'Principiante', 'Una pierna a la vez, mayor concentracion.', '/exercises/156.jpg'),
  ('Prensa de Piernas (Leg Press) 45', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Maquina', 'Empuje bilateral 45', 'Principiante', 'Angulo 45, pies en la plataforma.', '/exercises/157.jpg'),
  ('Prensa de Piernas Horizontal', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Maquina', 'Empuje bilateral horizontal', 'Principiante', 'Angulo horizontal, diferente tension en la articulacion.', '/exercises/158.jpg'),
  ('Hack Squat en Maquina', 'Cuadriceps', ARRAY['Gluteos'], 'Maquina', 'Sentadilla guiada', 'Principiante', 'Espalda contra el pad inclinado.', '/exercises/159.jpg'),
  ('Pendulum Squat', 'Cuadriceps', ARRAY['Gluteos'], 'Maquina', 'Sentadilla en arco', 'Intermedio', 'Maquina de arco pendular, excelente para cuadriceps sin carga en la columna.', '/exercises/160.jpg'),
  ('Belt Squat (Sentadilla con Cinto)', 'Cuadriceps', ARRAY['Gluteos'], 'Maquina', 'Sentadilla sin carga en columna', 'Intermedio', 'La carga se cuelga del cinto en la cadera, sin carga en columna.', '/exercises/161.jpg'),
  ('Sissy Squat', 'Cuadriceps', ARRAY[]::text[], 'Maquina', 'Extension de rodilla de pie', 'Avanzado', 'Inclinarse hacia atras mientras las rodillas avanzan hacia adelante.', '/exercises/162.jpg'),
  ('Sentadilla en Maquina Smith', 'Cuadriceps', ARRAY['Gluteos'], 'Maquina Smith', 'Sentadilla guiada', 'Principiante', 'Barra guiada.', '/exercises/163.jpg'),
  ('Sentadilla Libre (Sin peso)', 'Cuadriceps', ARRAY['Gluteos', 'Core'], 'Peso Corporal', 'Sentadilla', 'Principiante', 'Pies a la anchura de los hombros.', '/exercises/164.jpg'),
  ('Sentadilla Bulgara', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Peso Corporal', 'Zancada dividida', 'Intermedio', 'Pie trasero elevado en banco.', '/exercises/165.jpg'),
  ('Pistol Squat', 'Cuadriceps', ARRAY['Gluteos', 'Core'], 'Peso Corporal', 'Sentadilla unilateral', 'Avanzado', 'Sentadilla con una sola pierna.', '/exercises/166.jpg'),
  ('Box Squat', 'Cuadriceps', ARRAY['Gluteos', 'Isquiotibiales'], 'Peso Corporal', 'Sentadilla a caja', 'Intermedio', 'Sentarse sobre una caja/banco y volver a subir.', '/exercises/167.jpg'),
  ('Jump Squat', 'Cuadriceps', ARRAY['Gluteos', 'Core'], 'Peso Corporal', 'Sentadilla explosiva', 'Intermedio', 'Sentadilla profunda y saltar explosivamente.', '/exercises/168.jpg'),
  ('Curl de Piernas Tumbado', 'Isquiotibiales', ARRAY['Gastrocnemio'], 'Maquina', 'Flexion de rodilla', 'Principiante', 'Tumbado boca abajo, curvar los talones hacia los gluteos.', '/exercises/169.jpg'),
  ('Curl de Piernas Sentado', 'Isquiotibiales', ARRAY[]::text[], 'Maquina', 'Flexion de rodilla', 'Principiante', 'Sentado, tension constante en todo el rango.', '/exercises/170.jpg'),
  ('Curl de Piernas De Pie Unilateral', 'Isquiotibiales', ARRAY[]::text[], 'Maquina', 'Flexion de rodilla unilateral', 'Principiante', 'De pie, una pierna a la vez.', '/exercises/171.jpg'),
  ('Nordic Curl', 'Isquiotibiales', ARRAY[]::text[], 'Peso Corporal', 'Flexion de rodilla excentrica', 'Avanzado', 'Talones sujetos, descender lentamente controlando la caida.', '/exercises/172.jpg'),
  ('Curl de Isquios con Cable (Tumbado)', 'Isquiotibiales', ARRAY[]::text[], 'Cable', 'Flexion de rodilla', 'Principiante', 'Tobillera, tumbado, curvar la rodilla hacia el gluteo.', '/exercises/173.jpg'),
  ('Curl de Isquios con Cable (De Pie)', 'Isquiotibiales', ARRAY[]::text[], 'Cable', 'Flexion de rodilla de pie', 'Principiante', 'Tobillera, de pie, curvar la rodilla.', '/exercises/174.jpg'),
  ('Hip Thrust con Barra', 'Gluteos', ARRAY['Isquiotibiales', 'Cuadriceps'], 'Barra', 'Extension de cadera', 'Intermedio', 'Espalda en banco, barra en cadera, empujar las caderas.', '/exercises/175.jpg'),
  ('Hip Thrust con Mancuerna', 'Gluteos', ARRAY['Isquiotibiales'], 'Mancuernas', 'Extension de cadera', 'Principiante', 'Mancuerna sobre la cadera.', '/exercises/176.jpg'),
  ('Abduccion de Cadera en Maquina', 'Gluteos (medio)', ARRAY['TFL'], 'Maquina', 'Abduccion de cadera sentado', 'Principiante', 'Separar las piernas contra la resistencia.', '/exercises/177.jpg'),
  ('Aduccion de Cadera en Maquina', 'Aductores', ARRAY['Gluteos'], 'Maquina', 'Aduccion de cadera sentado', 'Principiante', 'Juntar las piernas contra la resistencia.', '/exercises/178.jpg'),
  ('Extension de Cadera en Maquina', 'Gluteos', ARRAY['Isquiotibiales'], 'Maquina', 'Extension de cadera', 'Principiante', 'De pie o inclinado, extender la pierna hacia atras.', '/exercises/179.jpg'),
  ('Hip Thrust en Maquina', 'Gluteos', ARRAY['Isquiotibiales'], 'Maquina', 'Extension de cadera guiada', 'Principiante', 'Maquina especifica de hip thrust.', '/exercises/180.jpg'),
  ('Cable Kickback', 'Gluteos', ARRAY['Isquiotibiales'], 'Cable', 'Extension de cadera', 'Principiante', 'Tobillera, polea baja, extender la pierna hacia atras.', '/exercises/181.jpg'),
  ('Hip Thrust con Cable', 'Gluteos', ARRAY['Isquiotibiales'], 'Cable', 'Extension de cadera con cable', 'Intermedio', 'Cable entre las piernas, empujar las caderas hacia arriba.', '/exercises/182.jpg'),
  ('Puente de Gluteos', 'Gluteos', ARRAY['Isquiotibiales', 'Core'], 'Peso Corporal', 'Extension de cadera', 'Principiante', 'Tumbado, pies apoyados, elevar las caderas.', '/exercises/183.jpg'),
  ('Hip Thrust con Peso Corporal', 'Gluteos', ARRAY['Isquiotibiales'], 'Peso Corporal', 'Extension de cadera', 'Principiante', 'Espalda en banco, sin peso adicional.', '/exercises/184.jpg'),
  ('Donkey Kicks', 'Gluteos', ARRAY[]::text[], 'Peso Corporal', 'Extension de cadera en cuadrupedia', 'Principiante', 'En cuatro apoyos, llevar el talon hacia el techo.', '/exercises/185.jpg'),
  ('Fire Hydrant', 'Gluteos (medio)', ARRAY[]::text[], 'Peso Corporal', 'Abduccion de cadera en cuadrupedia', 'Principiante', 'En cuatro apoyos, elevar la rodilla hacia afuera como un perro.', '/exercises/186.jpg'),
  ('Monster Walk', 'Gluteos (medio)', ARRAY['TFL'], 'Bandas Elasticas', 'Abduccion dinamica', 'Principiante', 'Banda en rodillas, pasos laterales.', '/exercises/187.jpg'),
  ('Elevacion de Talones con Mancuernas', 'Gastrocnemio', ARRAY['Soleo'], 'Mancuernas', 'Flexion plantar', 'Principiante', 'Mancuernas a los costados.', '/exercises/188.jpg'),
  ('Elevacion de Talones De Pie en Maquina', 'Gastrocnemio', ARRAY['Soleo'], 'Maquina', 'Flexion plantar', 'Principiante', 'Hombros bajo los pads.', '/exercises/189.jpg'),
  ('Elevacion de Talones Sentado en Maquina', 'Soleo', ARRAY['Gastrocnemio'], 'Maquina', 'Flexion plantar sentado', 'Principiante', 'Rodillas a 90, enfasis en soleo.', '/exercises/190.jpg'),
  ('Elevacion de Talones en Leg Press', 'Gastrocnemio', ARRAY['Soleo'], 'Maquina', 'Flexion plantar en prensa', 'Principiante', 'Solo la parte delantera del pie en la plataforma.', '/exercises/191.jpg'),
  ('Elevacion de Talones en Smith', 'Gastrocnemio', ARRAY['Soleo'], 'Maquina Smith', 'Flexion plantar', 'Principiante', 'Barra guiada, pies en una plataforma.', '/exercises/192.jpg'),
  ('Encogimientos con Barra (Shrugs)', 'Trapecios', ARRAY['Elevador de la Escapula'], 'Barra', 'Elevacion de escapula', 'Principiante', 'Barra frente al cuerpo, elevar los hombros sin rotar.', '/exercises/193.jpg'),
  ('Encogimientos Detras de la Espalda', 'Trapecios', ARRAY['Elevador de la Escapula'], 'Barra', 'Elevacion de escapula posterior', 'Intermedio', 'Barra detras del cuerpo, mayor rango posterior.', '/exercises/194.jpg'),
  ('Encogimientos con Mancuernas', 'Trapecios', ARRAY['Elevador de la Escapula'], 'Mancuernas', 'Elevacion de escapula', 'Principiante', 'Mancuernas a los costados.', '/exercises/195.jpg'),
  ('Encogimientos con Mancuernas Unilateral', 'Trapecios', ARRAY['Elevador de la Escapula'], 'Mancuernas', 'Elevacion de escapula unilateral', 'Principiante', 'Un hombro a la vez.', '/exercises/196.jpg'),
  ('Encogimientos en Maquina Smith', 'Trapecios', ARRAY[]::text[], 'Maquina Smith', 'Elevacion de escapula guiada', 'Principiante', 'Barra guiada.', '/exercises/197.jpg'),
  ('Encogimientos con Cable (Polea Baja)', 'Trapecios', ARRAY[]::text[], 'Cable', 'Elevacion de escapula', 'Principiante', 'Polea baja, tension constante.', '/exercises/198.jpg'),
  ('Face Pull (Trapecios)', 'Trapecios', ARRAY['Hombros (posterior)', 'Manguito Rotador'], 'Cable', 'Traccion diagonal', 'Principiante', 'Polea alta, tirar hacia la cara separando las manos.', '/exercises/199.jpg'),
  ('Remo al Menton con Cable', 'Trapecios', ARRAY['Hombros (lateral)', 'Biceps'], 'Cable', 'Traccion vertical', 'Intermedio', 'Polea baja, misma mecanica que con barra.', '/exercises/200.jpg'),
  ('Plancha Frontal', 'Core', ARRAY['Hombros', 'Gluteos'], 'Peso Corporal', 'Isometria frontal', 'Principiante', 'Antebrazos en el suelo, cuerpo recto.', '/exercises/201.jpg'),
  ('Plancha Lateral', 'Oblicuos', ARRAY['Core', 'Abductores'], 'Peso Corporal', 'Isometria lateral', 'Principiante', 'Un antebrazo en el suelo, cuerpo lateral recto.', '/exercises/202.jpg'),
  ('Plancha RKC (Cuerpo Tenso)', 'Core', ARRAY['Gluteos', 'Cuadriceps'], 'Peso Corporal', 'Isometria de alta tension', 'Intermedio', 'Plancha con maximo tension en todo el cuerpo.', '/exercises/203.jpg'),
  ('Crunch Abdominal', 'Recto Abdominal', ARRAY['Oblicuos'], 'Peso Corporal', 'Flexion de columna', 'Principiante', 'Elevar solo los hombros contrayendo el abdomen.', '/exercises/204.jpg'),
  ('Crunch Inverso', 'Recto Abdominal (inferior)', ARRAY['Core'], 'Peso Corporal', 'Flexion de cadera/columna', 'Principiante', 'Elevar la pelvis llevando rodillas al pecho.', '/exercises/205.jpg'),
  ('Crunch Bicicleta', 'Oblicuos', ARRAY['Recto Abdominal'], 'Peso Corporal', 'Rotacion + flexion', 'Principiante', 'Llevar codo hacia rodilla opuesta alternando.', '/exercises/206.jpg'),
  ('Crunch en Polea Alta', 'Recto Abdominal', ARRAY['Oblicuos'], 'Cable', 'Flexion de columna', 'Principiante', 'De rodillas frente a la polea, contraer el abdomen.', '/exercises/207.jpg'),
  ('Crunch con Peso (Plato)', 'Recto Abdominal', ARRAY['Oblicuos'], 'Maquina', 'Flexion de columna con carga', 'Intermedio', 'Sujetar un plato detras de la cabeza.', '/exercises/208.jpg'),
  ('Elevacion de Piernas', 'Recto Abdominal (inferior)', ARRAY['Iliopsoas', 'Core'], 'Peso Corporal', 'Flexion de cadera', 'Intermedio', 'Tumbado, elevar piernas juntas hasta 90.', '/exercises/209.jpg'),
  ('Elevacion de Piernas Colgando (Hanging Leg Raise)', 'Recto Abdominal (inferior)', ARRAY['Iliopsoas', 'Core'], 'Peso Corporal', 'Flexion de cadera colgando', 'Avanzado', 'Colgando de la barra, elevar piernas hasta 90 o mas.', '/exercises/210.jpg'),
  ('Elevacion de Rodillas Colgando', 'Recto Abdominal (inferior)', ARRAY['Iliopsoas'], 'Peso Corporal', 'Flexion de cadera colgando', 'Intermedio', 'Version mas facil que el de piernas estiradas.', '/exercises/211.jpg'),
  ('Elevacion de Piernas en Silla Romana', 'Recto Abdominal (inferior)', ARRAY['Iliopsoas'], 'Maquina', 'Flexion de cadera con soporte', 'Principiante', 'Antebrazos apoyados, elevar rodillas o piernas estiradas.', '/exercises/212.jpg'),
  ('Dragon Flag', 'Core', ARRAY['Espalda Baja', 'Hombros'], 'Peso Corporal', 'Isometria/Flexion de cuerpo entero', 'Avanzado', 'Tumbado en banco, bajar el cuerpo recto desde los hombros.', '/exercises/213.jpg'),
  ('Mountain Climbers', 'Core', ARRAY['Hombros', 'Cuadriceps'], 'Peso Corporal', 'Dinamico de core', 'Principiante', 'Plancha alta, llevar rodillas al pecho alternando.', '/exercises/214.jpg'),
  ('Dead Bug', 'Core', ARRAY['Espalda Baja'], 'Peso Corporal', 'Estabilizacion antiextension', 'Principiante', 'Tumbado, extender brazo y pierna opuestos.', '/exercises/215.jpg'),
  ('Ab Wheel Rollout', 'Core', ARRAY['Dorsal', 'Hombros'], 'Peso Corporal', 'Antiextension dinamica', 'Avanzado', 'Rueda abdominal, extender brazos manteniendo columna neutra.', '/exercises/216.jpg'),
  ('Ab Wheel desde Rodillas', 'Core', ARRAY['Dorsal', 'Hombros'], 'Peso Corporal', 'Antiextension dinamica', 'Intermedio', 'Version mas facil de rodillas.', '/exercises/217.jpg'),
  ('Rotacion de Tronco con Cable', 'Oblicuos', ARRAY['Core'], 'Cable', 'Rotacion de tronco', 'Principiante', 'Polea media, rotar el tronco.', '/exercises/218.jpg'),
  ('Russian Twist', 'Oblicuos', ARRAY['Core'], 'Peso Corporal', 'Rotacion de tronco', 'Principiante', 'Sentado inclinado, rotar el tronco de lado a lado.', '/exercises/219.jpg'),
  ('Cable Crunch', 'Recto Abdominal', ARRAY['Oblicuos'], 'Cable', 'Flexion de columna', 'Principiante', 'De rodillas frente a la polea alta, flexionar el tronco.', '/exercises/220.jpg'),
  ('Curl de Muneca con Barra Supino', 'Flexores del Antebrazo', ARRAY['Biceps'], 'Barra', 'Flexion de muneca', 'Principiante', 'Antebrazos apoyados en banco, flexionar la muneca.', '/exercises/221.jpg'),
  ('Curl de Muneca con Barra Prono', 'Extensores del Antebrazo', ARRAY[]::text[], 'Barra', 'Extension de muneca', 'Principiante', 'Antebrazos apoyados, extender la muneca.', '/exercises/222.jpg'),
  ('Curl de Muneca con Mancuerna', 'Flexores del Antebrazo', ARRAY[]::text[], 'Mancuernas', 'Flexion de muneca', 'Principiante', 'Antebrazo apoyado en el muslo.', '/exercises/223.jpg'),
  ('Extension de Muneca con Mancuerna', 'Extensores del Antebrazo', ARRAY[]::text[], 'Mancuernas', 'Extension de muneca', 'Principiante', 'Antebrazo apoyado, extender la muneca hacia arriba.', '/exercises/224.jpg'),
  ('Curl de Muneca con Cable', 'Flexores del Antebrazo', ARRAY[]::text[], 'Cable', 'Flexion de muneca', 'Principiante', 'Polea baja, tension constante.', '/exercises/225.jpg'),
  ('Extension de Muneca con Cable', 'Extensores del Antebrazo', ARRAY[]::text[], 'Cable', 'Extension de muneca', 'Principiante', 'Polea baja, extension de muneca.', '/exercises/226.jpg'),
  ('Reverse Curl con Barra', 'Braquiorradial', ARRAY['Extensores del Antebrazo'], 'Barra', 'Flexion de codo prono', 'Principiante', 'Agarre prono, curvar la barra hacia arriba.', '/exercises/227.jpg'),
  ('Wrist Roller', 'Antebrazo', ARRAY[]::text[], 'Maquina', 'Flexion/extension alternada de muneca', 'Principiante', 'Rollo con cuerda y peso, enrollar y desenrollar.', '/exercises/228.jpg'),
  ('Zancada Lateral', 'Aductores', ARRAY['Gluteos', 'Cuadriceps'], 'Peso Corporal', 'Zancada lateral', 'Principiante', 'Paso lateral amplio, doblar la rodilla de carga.', '/exercises/229.jpg'),
  ('Lateral Squat', 'Aductores', ARRAY['Gluteos', 'Cuadriceps'], 'Peso Corporal', 'Sentadilla lateral', 'Intermedio', 'Ampliar la zancada lateral y bajar profundo.', '/exercises/230.jpg'),
  ('Extension de Espalda Baja en Maquina', 'Espalda Baja', ARRAY['Gluteos', 'Isquiotibiales'], 'Maquina', 'Extension de columna', 'Principiante', 'Sentado, extender la columna contra la resistencia.', '/exercises/231.jpg'),
  ('Bird Dog', 'Espalda Baja', ARRAY['Gluteos', 'Core'], 'Peso Corporal', 'Estabilizacion en cuadrupedia', 'Principiante', 'En cuatro apoyos, extender brazo y pierna opuestos.', '/exercises/232.jpg'),
  ('Cat-Cow (Movilidad)', 'Espalda Baja', ARRAY['Core'], 'Peso Corporal', 'Movilidad de columna', 'Principiante', 'En cuatro apoyos, alternar flexion y extension de columna.', '/exercises/233.jpg'),
  ('Swing con Kettlebell (Dos Manos)', 'Gluteos', ARRAY['Isquiotibiales', 'Core', 'Espalda Baja'], 'Kettlebell', 'Bisagra de cadera explosiva', 'Intermedio', 'Bisagra explosiva, swing hasta la altura de los hombros.', '/exercises/234.jpg'),
  ('Swing con Kettlebell (Un Brazo)', 'Gluteos', ARRAY['Isquiotibiales', 'Core', 'Hombros'], 'Kettlebell', 'Bisagra de cadera explosiva unilateral', 'Intermedio', 'Mayor rotacion y estabilizacion.', '/exercises/235.jpg'),
  ('Goblet Squat con Kettlebell', 'Cuadriceps', ARRAY['Gluteos', 'Core'], 'Kettlebell', 'Sentadilla frontal', 'Principiante', 'Kettlebell frente al pecho, torso erguido.', '/exercises/236.jpg'),
  ('Clamshell con Banda', 'Gluteos (medio)', ARRAY[]::text[], 'Bandas Elasticas', 'Rotacion externa de cadera', 'Principiante', 'Tumbado de lado, abrir como una almeja.', '/exercises/237.jpg'),
  ('TRX Pistol Squat Asistido', 'Cuadriceps', ARRAY['Gluteos'], 'TRX / Suspension', 'Sentadilla unilateral asistida', 'Intermedio', 'Usar los mangos como soporte.', '/exercises/238.jpg'),
  ('TRX Pike', 'Core', ARRAY['Hombros'], 'TRX / Suspension', 'Flexion de cadera en suspension', 'Avanzado', 'Pies en los mangos, llevar caderas hacia arriba.', '/exercises/239.jpg'),
  ('Clean and Jerk', 'Gluteos', ARRAY['Cuadriceps', 'Hombros', 'Core', 'Isquiotibiales'], 'Barra', 'Movimiento olimpico completo', 'Avanzado', 'Levantar la barra del suelo a los hombros (clean) y luego sobre la cabeza (jerk).', '/exercises/240.jpg'),
  ('Snatch', 'Gluteos', ARRAY['Cuadriceps', 'Hombros', 'Core', 'Isquiotibiales'], 'Barra', 'Movimiento olimpico completo', 'Avanzado', 'Levantar la barra del suelo a sobre la cabeza en un solo movimiento.', '/exercises/241.jpg'),
  ('Power Clean', 'Gluteos', ARRAY['Cuadriceps', 'Isquiotibiales', 'Core', 'Hombros'], 'Barra', 'Movimiento de potencia', 'Avanzado', 'Clean sin caer bajo la barra, quedando de pie.', '/exercises/242.jpg'),
  ('Power Snatch', 'Gluteos', ARRAY['Cuadriceps', 'Isquiotibiales', 'Hombros'], 'Barra', 'Movimiento de potencia', 'Avanzado', 'Snatch sin caer en sentadilla.', '/exercises/243.jpg'),
  ('Hang Clean', 'Gluteos', ARRAY['Cuadriceps', 'Isquiotibiales', 'Hombros'], 'Barra', 'Movimiento olimpico desde hang', 'Avanzado', 'Clean comenzando desde la posicion de hang (barra a la altura del muslo).', '/exercises/244.jpg'),
  ('Hang Power Clean', 'Gluteos', ARRAY['Cuadriceps', 'Isquiotibiales', 'Hombros'], 'Barra', 'Movimiento de potencia desde hang', 'Avanzado', 'Power clean desde posicion de hang.', '/exercises/245.jpg'),
  ('High Pull', 'Trapecios', ARRAY['Hombros', 'Isquiotibiales', 'Gluteos'], 'Barra', 'Tiracion explosiva vertical', 'Avanzado', 'Tiracion de barra desde el suelo hasta la barbilla con impulso de caderas.', '/exercises/246.jpg'),
  ('Split Jerk', 'Hombros', ARRAY['Cuadriceps', 'Core'], 'Barra', 'Empuje vertical con separacion de piernas', 'Avanzado', 'Caer con una pierna adelante y otra atras al extender los brazos.', '/exercises/247.jpg'),
  ('Landmine Squat to Press', 'Cuadriceps', ARRAY['Gluteos', 'Hombros', 'Core'], 'Barra', 'Compuesto de sentadilla + press', 'Intermedio', 'Un extremo de la barra anclado, sentadilla y press en un movimiento.', '/exercises/248.jpg'),
  ('Maquina de Hombros (Lateral Raise)', 'Hombros (lateral)', ARRAY['Trapecios'], 'Maquina', 'Aislamiento lateral', 'Principiante', 'Tension constante a lo largo de todo el rango.', '/exercises/249.jpg'),
  ('Rower (Maquina de Remo)', 'Espalda Alta', ARRAY['Biceps', 'Cuadriceps', 'Gluteos'], 'Maquina', 'Cardio-fuerza de remo', 'Intermedio', 'Maquina de remo de resistencia, trabaja cuerpo completo.', '/exercises/250.jpg'),
  ('Maquina Battle Rope', 'Core', ARRAY['Hombros', 'Espalda Alta'], 'Maquina', 'Cardio-fuerza con cuerdas', 'Intermedio', 'Cuerdas pesadas, movimientos ondulatorios de brazos.', '/exercises/251.jpg'),
  ('AirBike (Bicicleta de Aire)', 'Cuadriceps', ARRAY['Gluteos', 'Hombros', 'Core'], 'Maquina', 'Cardio-fuerza cuerpo completo', 'Principiante', 'Bicicleta con palancas para los brazos, resistencia por aire.', '/exercises/252.jpg');
