/**
 * Diccionario de sinónimos para la búsqueda de ejercicios.
 * Clave: término que puede escribir el usuario.
 * Valor: array de términos adicionales que se agregan al query.
 *
 * El matching es substring case-insensitive: si el usuario escribe "polea",
 * se busca también "cable" en el índice Fuse.
 */
export const EXERCISE_SYNONYMS: Record<string, string[]> = {
  // ── Equipamiento ──────────────────────────────────────────────────────────
  polea:      ["cable"],
  poleas:     ["cable"],
  "cable":    ["polea"],
  pesa:       ["mancuerna"],
  pesas:      ["mancuerna", "mancuernas"],
  barra:      ["barbell"],
  barbell:    ["barra"],
  dumbbell:   ["mancuerna"],
  dumbbells:  ["mancuernas"],
  kettlebell: ["pesa rusa"],
  "pesa rusa":["kettlebell"],
  banda:      ["bandas elasticas", "elastic"],
  bandas:     ["bandas elasticas"],
  elastic:    ["bandas elasticas", "banda"],
  trx:        ["suspension", "trx"],
  suspension: ["trx"],
  maquina:    ["machine", "máquina"],
  máquina:    ["maquina", "machine"],
  machine:    ["maquina"],
  smith:      ["maquina smith"],
  bodyweight: ["peso corporal"],
  "peso corporal": ["bodyweight", "cuerpo"],
  cuerpo:     ["peso corporal"],

  // ── Grupos musculares ─────────────────────────────────────────────────────
  espalda:    ["dorsal", "espalda alta", "espalda baja", "back"],
  back:       ["dorsal", "espalda alta", "espalda baja"],
  dorsal:     ["espalda", "lat", "lats"],
  lats:       ["dorsal", "jalon"],
  lat:        ["dorsal", "jalon"],
  pecho:      ["chest", "pectoral"],
  chest:      ["pecho", "press"],
  pectoral:   ["pecho"],
  hombro:     ["hombros", "shoulder", "deltoid"],
  hombros:    ["shoulder", "deltoid"],
  shoulder:   ["hombros", "deltoid"],
  deltoid:    ["hombros", "elevacion"],
  bicep:      ["biceps", "curl"],
  biceps:     ["bicep", "curl"],
  tricep:     ["triceps", "extension"],
  triceps:    ["tricep", "extension"],
  gluteo:     ["gluteos", "glute", "cadera"],
  glúteo:     ["gluteos"],
  gluteos:    ["glute", "cadera"],
  glute:      ["gluteos"],
  pierna:     ["cuadriceps", "isquiotibiales", "gluteos", "leg"],
  piernas:    ["cuadriceps", "isquiotibiales", "gluteos", "leg"],
  leg:        ["cuadriceps", "isquiotibiales"],
  cuad:       ["cuadriceps"],
  quad:       ["cuadriceps"],
  quads:      ["cuadriceps"],
  isquio:     ["isquiotibiales", "hamstring"],
  isquios:    ["isquiotibiales"],
  hamstring:  ["isquiotibiales"],
  pantorrilla:["gastrocnemio", "soleo", "calf"],
  calf:       ["gastrocnemio", "soleo"],
  calves:     ["gastrocnemio", "soleo", "elevacion de talones"],
  core:       ["abdomen", "abdominal", "plancha"],
  abdomen:    ["core", "abdominal", "crunch"],
  abs:        ["core", "recto abdominal", "crunch"],
  oblicuos:   ["obliquo", "oblique"],
  trapecio:   ["trapecios", "trap"],
  trapecios:  ["trap"],
  trap:       ["trapecios", "encogimiento"],
  lumbar:     ["espalda baja", "lower back"],

  // ── Movimientos / ejercicios por alias ───────────────────────────────────
  press:      ["empuje", "push"],
  push:       ["press", "empuje"],
  pull:       ["jalon", "traccion", "dominadas"],
  jalon:      ["lat pulldown", "jalón", "cable"],
  jalón:      ["jalon", "lat pulldown"],
  "lat pulldown": ["jalon", "dorsal"],
  pulldown:   ["jalon", "dorsal"],
  remo:       ["row", "traccion horizontal"],
  row:        ["remo", "traccion"],
  curl:       ["flexion de codo", "biceps"],
  squat:      ["sentadilla"],
  sentadilla: ["squat"],
  deadlift:   ["peso muerto"],
  "peso muerto": ["deadlift", "rdl", "rumano"],
  rdl:        ["peso muerto rumano", "rumano"],
  rumano:     ["rdl", "peso muerto rumano"],
  "hip thrust": ["empuje de cadera", "puente de gluteos"],
  "hip hinge":  ["peso muerto", "bisagra de cadera", "buenos dias"],
  zancada:    ["lunge", "estocada"],
  lunge:      ["zancada", "estocada"],
  estocada:   ["zancada", "lunge"],
  plancha:    ["plank", "isometria"],
  plank:      ["plancha"],
  dominadas:  ["pull-up", "pullup", "chin-up", "chinup"],
  "pull-up":  ["dominadas"],
  pullup:     ["dominadas"],
  "chin-up":  ["dominadas agarre supino"],
  chinup:     ["dominadas agarre supino"],
  fondos:     ["dips", "paralelas"],
  dips:       ["fondos", "paralelas"],
  extensión:  ["extension"],
  extension:  ["extensión", "triceps"],
  elevacion:  ["raise", "elevación"],
  "face pull":["remo hacia la cara", "deltoid posterior"],
  encogimiento: ["shrug", "trapecio"],
  shrug:      ["encogimiento", "trapecios"],
  hiperextension: ["hyperextension", "espalda baja"],
  hyperextension: ["hiperextension"],
  crunch:     ["abdominal", "flexion de columna"],
  abdominal:  ["crunch", "core", "abs"],
  burpee:     ["burpees"],
  burpees:    ["burpee"],
  swing:      ["kettlebell", "bisagra de cadera"],
  goblet:     ["sentadilla goblet", "kettlebell"],
  military:   ["press militar"],
  "press militar": ["military press", "overhead press", "ohp"],
  ohp:        ["press militar", "overhead press"],
  overhead:   ["press militar", "sobre la cabeza"],
  romanian:   ["rumano", "peso muerto rumano"],
  "good morning": ["buenos dias", "bisagra de cadera"],
  "buenos dias":  ["good morning"],
  "step up":  ["step-up", "escalonado"],
  "step-up":  ["step up", "escalonado"],
  sumo:       ["sentadilla sumo", "peso muerto sumo"],
  arnold:     ["press arnold"],
  skullcrusher: ["press frances", "triceps"],
  "press frances": ["skullcrusher", "triceps"],
  nordico:    ["nordic curl", "isquiotibiales"],
  "nordic curl": ["nordico", "isquiotibiales"],
  farmer:     ["farmer walk", "caminata"],
  pallof:     ["pallof press", "antirrotacion"],
  rollout:    ["ab wheel", "rodillo abdominal"],
  "ab wheel": ["rollout", "rodillo"],
}
