/**
 * Sistema de frases motivacionales / reflexivas.
 * Dominio puro — sin dependencias de React/Next.
 *
 * Las frases están en código para el MVP.
 * En el futuro se puede conectar a una tabla en Supabase o una API externa.
 */

// ─── Categorías ──────────────────────────────────────────────────────────────

export const QUOTE_CATEGORIES = [
  "fitness",
  "estoicismo",
  "biblia",
  "budismo",
  "hinduismo",
  "filosofia",
  "reflexion",
  "mentalidad",
  "motivacion",
  "fisicoculturistas",
] as const

export type QuoteCategory = (typeof QUOTE_CATEGORIES)[number]

export type QuoteCategoryMeta = {
  key: QuoteCategory
  label: string
  description: string
  spiritual: boolean  // para agrupar en la UI
}

export const QUOTE_CATEGORY_META: Record<QuoteCategory, QuoteCategoryMeta> = {
  fitness: {
    key: "fitness",
    label: "Fitness & Disciplina",
    description: "Entrenamiento, constancia y superación física",
    spiritual: false,
  },
  estoicismo: {
    key: "estoicismo",
    label: "Estoicismo",
    description: "Marco Aurelio, Epicteto, Séneca",
    spiritual: false,
  },
  biblia: {
    key: "biblia",
    label: "Versículos bíblicos",
    description: "Escrituras del Antiguo y Nuevo Testamento",
    spiritual: true,
  },
  budismo: {
    key: "budismo",
    label: "Budismo",
    description: "Buda, mindfulness y paz interior",
    spiritual: true,
  },
  hinduismo: {
    key: "hinduismo",
    label: "Hinduismo",
    description: "Bhagavad Gita, sabiduría védica",
    spiritual: true,
  },
  filosofia: {
    key: "filosofia",
    label: "Filosofía clásica",
    description: "Aristóteles, Platón, Nietzsche, Camus",
    spiritual: false,
  },
  reflexion: {
    key: "reflexion",
    label: "Reflexión general",
    description: "Pensamientos sobre la vida y el propósito",
    spiritual: false,
  },
  mentalidad: {
    key: "mentalidad",
    label: "Mentalidad & Enfoque",
    description: "Claridad mental, hábitos y rendimiento",
    spiritual: false,
  },
  motivacion: {
    key: "motivacion",
    label: "Motivación fuerte",
    description: "Frases de impacto y acción inmediata",
    spiritual: false,
  },
  fisicoculturistas: {
    key: "fisicoculturistas",
    label: "Fisicoculturistas",
    description: "Sabiduría de campeones del fisicoculturismo",
    spiritual: false,
  },
}

export const QUOTE_CATEGORY_LIST = QUOTE_CATEGORIES.map(
  (k) => QUOTE_CATEGORY_META[k],
)

// ─── Tipo de frase ────────────────────────────────────────────────────────────

export type Quote = {
  id: string
  text: string
  author: string | null   // null = anónimo
  source: string | null   // libro, obra, ref
  category: QuoteCategory
}

// ─── Base de frases (Completa con 600+ frases) ───────────────────────────────

export const QUOTES: Quote[] = [
  // ── Fitness & Disciplina (103) ───────────────────────────────────────────
  { id: "fit1", text: "La disciplina es el puente entre los objetivos y los logros.", author: "Jim Rohn", source: null, category: "fitness" },
  { id: "fit2", text: "No hay atajo para la excelencia, solo hay trabajo duro.", author: "Ralph Marston", source: null, category: "fitness" },
  { id: "fit3", text: "El cuerpo logra lo que la mente cree.", author: "Arnold Schwarzenegger", source: null, category: "fitness" },
  { id: "fit4", text: "La consistencia es lo que transforma la intención en realidad.", author: "James Clear", source: null, category: "fitness" },
  { id: "fit5", text: "Entrenar es lo más difícil en los primeros días, pero después se vuelve fácil.", author: "Muhammad Ali", source: null, category: "fitness" },
  { id: "fit6", text: "Tu cuerpo puede aguantar casi cualquier cosa. Es tu mente la que necesita convencerse.", author: "Bear Grylls", source: null, category: "fitness" },
  { id: "fit7", text: "El dolor que sientes hoy será la fortaleza que sentirás mañana.", author: "Arnold Schwarzenegger", source: null, category: "fitness" },
  { id: "fit8", text: "El único mal entrenamiento es el que no haces.", author: null, source: null, category: "fitness" },
  { id: "fit9", text: "La disciplina es recordar lo que realmente quieres.", author: "David Campbell", source: null, category: "fitness" },
  { id: "fit10", text: "No busques motivación, busca disciplina.", author: "Jocko Willink", source: null, category: "fitness" },
  { id: "fit11", text: "El que vence a sí mismo es más grande que el que conquista ciudades.", author: null, source: "Proverbios 16:32", category: "fitness" },
  { id: "fit12", text: "Tu mejor competencia eres tú mismo de ayer.", author: "James Clear", source: null, category: "fitness" },
  { id: "fit13", text: "La dedicación es la diferencia entre soñar y lograr.", author: null, source: null, category: "fitness" },
  { id: "fit14", text: "Cada repetición te acerca a tu meta.", author: null, source: null, category: "fitness" },
  { id: "fit15", text: "La fuerza viene de la consistencia, no de la intensidad ocasional.", author: null, source: null, category: "fitness" },
  { id: "fit16", text: "Entrena como si alguien estuviera pisándote los talones.", author: null, source: null, category: "fitness" },
  { id: "fit17", text: "Tu límite es solo tu imaginación.", author: null, source: null, category: "fitness" },
  { id: "fit18", text: "La verdadera fortaleza se construye en los momentos que quieres rendirte.", author: null, source: null, category: "fitness" },
  { id: "fit19", text: "Disciplina = libertad.", author: "Jocko Willink", source: null, category: "fitness" },
  { id: "fit20", text: "El éxito no es final, el fracaso no es fatal: es el valor de continuar lo que cuenta.", author: "Winston Churchill", source: null, category: "fitness" },
  { id: "fit21", text: "Sé más fuerte que tus excusas.", author: null, source: null, category: "fitness" },
  { id: "fit22", text: "El único progreso real es el que sientes en tus músculos.", author: null, source: null, category: "fitness" },
  { id: "fit23", text: "Entrena con un propósito, no con un ego.", author: null, source: null, category: "fitness" },
  { id: "fit24", text: "La paciencia es la clave para construir un cuerpo excepcional.", author: null, source: null, category: "fitness" },
  { id: "fit25", text: "El cuerpo que deseas requiere el trabajo que evitas.", author: null, source: null, category: "fitness" },
  { id: "fit26", text: "No esperes a sentirte listo, actúa y te sentirás listo.", author: "David Goggins", source: null, category: "fitness" },
  { id: "fit27", text: "El entrenamiento es el 40%, la nutrición es el 50%, y la consistencia es el 10% restante.", author: null, source: null, category: "fitness" },
  { id: "fit28", text: "La disciplina es hacer lo que necesitas hacer aunque no te apetezca.", author: null, source: null, category: "fitness" },
  { id: "fit29", text: "Tu cuerpo sigue tus órdenes. Da órdenes correctas.", author: null, source: null, category: "fitness" },
  { id: "fit30", text: "El dolor es temporal, el orgullo es eterno.", author: null, source: null, category: "fitness" },
  { id: "fit31", text: "Cada gota de sudor es un paso hacia tu transformación.", author: null, source: null, category: "fitness" },
  { id: "fit32", text: "La fortaleza se construye fuera del gimnasio, se prueba dentro del gimnasio.", author: null, source: null, category: "fitness" },
  { id: "fit33", text: "No necesitas ser el mejor en el día 1, necesitas ser consistente.", author: null, source: null, category: "fitness" },
  { id: "fit34", text: "El sacrificio de hoy es el éxito de mañana.", author: null, source: null, category: "fitness" },
  { id: "fit35", text: "Tu mente rendirse es mucho antes de que tu cuerpo lo haga.", author: null, source: null, category: "fitness" },
  { id: "fit36", text: "La excelencia es una práctica, no una coincidencia.", author: "Aristóteles", source: null, category: "fitness" },
  { id: "fit37", text: "El entrenador que no dudaría de ti no eres ni tú.", author: null, source: null, category: "fitness" },
  { id: "fit38", text: "La verdadera victoria es contra ti mismo.", author: null, source: null, category: "fitness" },
  { id: "fit39", text: "Toda semana que entrenas es una semana que invieres en ti.", author: null, source: null, category: "fitness" },
  { id: "fit40", text: "El cuerpo fuerte requiere una mente más fuerte.", author: null, source: null, category: "fitness" },
  { id: "fit41", text: "El trabajo duro no tiene atajo.", author: null, source: null, category: "fitness" },
  { id: "fit42", text: "No busques el camino más fácil, busca el que te haga más fuerte.", author: null, source: null, category: "fitness" },
  { id: "fit43", text: "El verdadero músculo es la disciplina.", author: null, source: null, category: "fitness" },
  { id: "fit44", text: "Cada entrenamiento es una oportunidad de superarte.", author: null, source: null, category: "fitness" },
  { id: "fit45", text: "La consistencia vence al talento cuando el talento no es consistente.", author: "Jeff Goins", source: null, category: "fitness" },
  { id: "fit46", text: "Tu cuerpo sigue a tu voluntad.", author: null, source: null, category: "fitness" },
  { id: "fit47", text: "El primer paso hacia cualquier meta es la decisión.", author: null, source: null, category: "fitness" },
  { id: "fit48", text: "La vida comienza donde termina tu zona de confort.", author: "Neale Donald Walsch", source: null, category: "fitness" },
  { id: "fit49", text: "El tiempo es tu recurso más valioso. Invierte en ti.", author: null, source: null, category: "fitness" },
  { id: "fit50", text: "No tienes que ser perfecto, solo tienes que empezar.", author: null, source: null, category: "fitness" },
  { id: "fit51", text: "La verdadera fortaleza viene del interior.", author: null, source: null, category: "fitness" },
  { id: "fit52", text: "El camino hacia la grandeza se pavimenta con pequeños pasos constantes.", author: null, source: null, category: "fitness" },
  { id: "fit53", text: "Tu cuerpo es una obra de arte. Trabaja en ello todos los días.", author: null, source: null, category: "fitness" },
  { id: "fit54", text: "El éxito no se mide en libras, se mide en persistencia.", author: null, source: null, category: "fitness" },
  { id: "fit55", text: "La disciplina es elegir lo que quieres más ahora que lo que quieres en este momento.", author: "Auguste Comte", source: null, category: "fitness" },
  { id: "fit56", text: "El verdadero crecimiento ocurre fuera de tu zona de confort.", author: null, source: null, category: "fitness" },
  { id: "fit57", text: "No esperes el momento perfecto, toma el momento e hazlo perfecto.", author: null, source: null, category: "fitness" },
  { id: "fit58", text: "Tu mayor competidor está en el espejo.", author: null, source: null, category: "fitness" },
  { id: "fit59", text: "La consistencia es la base de toda mejora.", author: null, source: null, category: "fitness" },
  { id: "fit60", text: "El esfuerzo nunca es en vano.", author: null, source: null, category: "fitness" },
  { id: "fit61", text: "Tu cuerpo refleja tu dedicación.", author: null, source: null, category: "fitness" },
  { id: "fit62", text: "El sudor es solo la grasa llorando.", author: null, source: null, category: "fitness" },
  { id: "fit63", text: "La disciplina es hacer lo correcto incluso cuando es difícil.", author: null, source: null, category: "fitness" },
  { id: "fit64", text: "La verdadera prueba es la consistencia a largo plazo.", author: null, source: null, category: "fitness" },
  { id: "fit65", text: "Cada entrenamiento es un inversión en tu salud futura.", author: null, source: null, category: "fitness" },
  { id: "fit66", text: "La fortaleza viene de superar lo que te asusta.", author: null, source: null, category: "fitness" },
  { id: "fit67", text: "Tu cuerpo no es el problema. Tu compromiso es la solución.", author: null, source: null, category: "fitness" },
  { id: "fit68", text: "El progreso es progreso, sin importar el tamaño.", author: null, source: null, category: "fitness" },
  { id: "fit69", text: "La disciplina es tu mejor amiga en el gimnasio.", author: null, source: null, category: "fitness" },
  { id: "fit70", text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali", source: null, category: "fitness" },
  { id: "fit71", text: "Tu límite es solo tu mente.", author: null, source: null, category: "fitness" },
  { id: "fit72", text: "El cuerpo fuerte es el resultado de la mente fuerte.", author: null, source: null, category: "fitness" },
  { id: "fit73", text: "Cada serie cuenta. Cada repetición importa.", author: null, source: null, category: "fitness" },
  { id: "fit74", text: "La verdadera fuerza es la capacidad de continuar cuando quieres parar.", author: null, source: null, category: "fitness" },
  { id: "fit75", text: "Tu mente es tu arma más poderosa.", author: null, source: null, category: "fitness" },
  { id: "fit76", text: "El entrenamiento es medicina para el cuerpo y el alma.", author: null, source: null, category: "fitness" },
  { id: "fit77", text: "La disciplina es la diferencia entre querer y tener.", author: null, source: null, category: "fitness" },
  { id: "fit78", text: "Cada gota de sudor cuenta.", author: null, source: null, category: "fitness" },
  { id: "fit79", text: "La consistencia convierte el sueño en realidad.", author: null, source: null, category: "fitness" },
  { id: "fit80", text: "Tu cuerpo es el templo de tu alma.", author: null, source: null, category: "fitness" },
  { id: "fit81", text: "No busques resultados rápidos, busca cambios permanentes.", author: null, source: null, category: "fitness" },
  { id: "fit82", text: "La verdadera victoria es privada, ante ti mismo.", author: null, source: null, category: "fitness" },
  { id: "fit83", text: "El trabajo que haces hoy construye el cuerpo de mañana.", author: null, source: null, category: "fitness" },
  { id: "fit84", text: "La disciplina es la libertad de ser quien quieres ser.", author: null, source: null, category: "fitness" },
  { id: "fit85", text: "Tu compromiso es más fuerte que tu dolor.", author: null, source: null, category: "fitness" },
  { id: "fit86", text: "La fortaleza se construye un entrenamiento a la vez.", author: null, source: null, category: "fitness" },
  { id: "fit87", text: "El cuerpo logra lo que la mente no se atreve a soñar.", author: null, source: null, category: "fitness" },
  { id: "fit88", text: "La disciplina es un hábito, no una limitación.", author: null, source: null, category: "fitness" },
  { id: "fit89", text: "Tu único límite es tu determinación.", author: null, source: null, category: "fitness" },
  { id: "fit90", text: "El éxito es la suma de pequeños esfuerzos constantes.", author: "Robert Collier", source: null, category: "fitness" },
  { id: "fit91", text: "La verdadera fuerza se construye en silencio.", author: null, source: null, category: "fitness" },
  { id: "fit92", text: "Cada entrenamiento te acerca a tu mejor versión.", author: null, source: null, category: "fitness" },
  { id: "fit93", text: "La disciplina es el precio de la excelencia.", author: null, source: null, category: "fitness" },
  { id: "fit94", text: "Tu cuerpo es el lienzo, el entrenamiento es el pincel.", author: null, source: null, category: "fitness" },
  { id: "fit95", text: "No abandones en el minuto 9 si quieres resultados en el minuto 10.", author: null, source: null, category: "fitness" },
  { id: "fit96", text: "La consistencia es más importante que la intensidad ocasional.", author: null, source: null, category: "fitness" },
  { id: "fit97", text: "Tu futuro es decidido por lo que haces hoy.", author: null, source: null, category: "fitness" },
  { id: "fit98", text: "La verdadera victoria es sobre ti mismo.", author: null, source: null, category: "fitness" },
  { id: "fit99", text: "Cada entrenamiento es una batalla ganada.", author: null, source: null, category: "fitness" },
  { id: "fit100", text: "La disciplina es vivir como si tu futuro importara.", author: null, source: null, category: "fitness" },
  { id: "fit101", text: "Tu compromiso supera tu miedo.", author: null, source: null, category: "fitness" },
  { id: "fit102", text: "El verdadero guerrero conquista su mente primero.", author: null, source: null, category: "fitness" },
  { id: "fit103", text: "Tu dedicación es tu mejor defensa contra el fracaso.", author: null, source: null, category: "fitness" },

  // ── Motivación fuerte (71) ────────────────────────────────────────────────
  { id: "mot1", text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs", source: null, category: "motivacion" },
  { id: "mot2", text: "No es sobre querer, es sobre hacer.", author: "Erich Fried", source: null, category: "motivacion" },
  { id: "mot3", text: "El futuro pertenece a los que creen en la belleza de sus sueños.", author: "Eleanor Roosevelt", source: null, category: "motivacion" },
  { id: "mot4", text: "Hoy es el primer día del resto de tu vida.", author: "Charles Dederoth", source: null, category: "motivacion" },
  { id: "mot5", text: "La mente es todo. Lo que piensas, lo que te conviertes.", author: "Buddha", source: null, category: "motivacion" },
  { id: "mot6", text: "El éxito es un viaje, no un destino.", author: "Arthur Ashe", source: null, category: "motivacion" },
  { id: "mot7", text: "No dejes para mañana lo que puedes hacer hoy.", author: "Benjamin Franklin", source: null, category: "motivacion" },
  { id: "mot8", text: "Créete digno de grandeza.", author: "Oprah Winfrey", source: null, category: "motivacion" },
  { id: "mot9", text: "La acción es el puente entre el sueño y la realidad.", author: null, source: null, category: "motivacion" },
  { id: "mot10", text: "Tu potencial es infinito.", author: null, source: null, category: "motivacion" },
  { id: "mot11", text: "La vida es ahora, no mañana.", author: "Jon Kabat-Zinn", source: null, category: "motivacion" },
  { id: "mot12", text: "Eres más fuerte de lo que crees.", author: null, source: null, category: "motivacion" },
  { id: "mot13", text: "No puedes cambiar el pasado, pero puedes cambiar el futuro.", author: null, source: null, category: "motivacion" },
  { id: "mot14", text: "La mejor versión de ti es la que luchas por ser.", author: null, source: null, category: "motivacion" },
  { id: "mot15", text: "Tu voz importa. Tu sueño importa. Tú importas.", author: null, source: null, category: "motivacion" },
  { id: "mot16", text: "No te compares con otros, compárate con quien eras ayer.", author: null, source: null, category: "motivacion" },
  { id: "mot17", text: "La vida es corta, hazla grandiosa.", author: null, source: null, category: "motivacion" },
  { id: "mot18", text: "Eres capaz de mucho más de lo que imaginas.", author: null, source: null, category: "motivacion" },
  { id: "mot19", text: "El cambio comienza contigo.", author: null, source: null, category: "motivacion" },
  { id: "mot20", text: "Sueña en grande, trabaja duro, logra más.", author: null, source: null, category: "motivacion" },
  { id: "mot21", text: "Tu historia es una inspiración.", author: null, source: null, category: "motivacion" },
  { id: "mot22", text: "No hay límite para lo que puedes lograr.", author: null, source: null, category: "motivacion" },
  { id: "mot23", text: "Cada día es una oportunidad para ser mejor.", author: null, source: null, category: "motivacion" },
  { id: "mot24", text: "La fe en ti mismo es el primer paso hacia el éxito.", author: null, source: null, category: "motivacion" },
  { id: "mot25", text: "Tu destino está en tus manos.", author: null, source: null, category: "motivacion" },
  { id: "mot26", text: "La persistencia siempre gana.", author: null, source: null, category: "motivacion" },
  { id: "mot27", text: "No esperes a estar listo, comienza ahora.", author: null, source: null, category: "motivacion" },
  { id: "mot28", text: "Eres una obra en progreso.", author: null, source: null, category: "motivacion" },
  { id: "mot29", text: "Tu mente es tu herramienta más poderosa.", author: null, source: null, category: "motivacion" },
  { id: "mot30", text: "La grandeza está dentro de ti.", author: null, source: null, category: "motivacion" },
  { id: "mot31", text: "Vive como si hoy fuera tu último día.", author: "Steve Jobs", source: null, category: "motivacion" },
  { id: "mot32", text: "La verdadera fuerza es la vulnerabilidad.", author: "Brené Brown", source: null, category: "motivacion" },
  { id: "mot33", text: "Tu pasado no define tu futuro.", author: null, source: null, category: "motivacion" },
  { id: "mot34", text: "Eres la respuesta a tus propias plegarias.", author: null, source: null, category: "motivacion" },
  { id: "mot35", text: "La vida es tu lienzo, pinta tu masterpiece.", author: null, source: null, category: "motivacion" },
  { id: "mot36", text: "Cree y lo lograrás.", author: null, source: null, category: "motivacion" },
  { id: "mot37", text: "No hay imposibles, solo hay imposibles pendientes.", author: null, source: null, category: "motivacion" },
  { id: "mot38", text: "Tú eres tu mayor limitación.", author: null, source: null, category: "motivacion" },
  { id: "mot39", text: "El tiempo no espera, tú tampoco deberías.", author: null, source: null, category: "motivacion" },
  { id: "mot40", text: "La vida recompensa a los valientes.", author: null, source: null, category: "motivacion" },
  { id: "mot41", text: "No temas al fracaso, teme al arrepentimiento.", author: null, source: null, category: "motivacion" },
  { id: "mot42", text: "Cada paso te acerca a tu destino.", author: null, source: null, category: "motivacion" },
  { id: "mot43", text: "Eres capaz de crear magia.", author: null, source: null, category: "motivacion" },
  { id: "mot44", text: "La vida es una aventura, vívela plenamente.", author: null, source: null, category: "motivacion" },
  { id: "mot45", text: "Tu éxito es tu responsabilidad.", author: null, source: null, category: "motivacion" },
  { id: "mot46", text: "Eres más que una limitación.", author: null, source: null, category: "motivacion" },
  { id: "mot47", text: "La vida te desafía para hacerte más fuerte.", author: null, source: null, category: "motivacion" },
  { id: "mot48", text: "Tú eres el dueño de tu destino.", author: null, source: null, category: "motivacion" },
  { id: "mot49", text: "No hay momento mejor que ahora.", author: null, source: null, category: "motivacion" },
  { id: "mot50", text: "La victoria es para los persistentes.", author: null, source: null, category: "motivacion" },
  { id: "mot51", text: "Tu sueño es tu realidad esperando.", author: null, source: null, category: "motivacion" },
  { id: "mot52", text: "Eres más fuerte que tus circunstancias.", author: null, source: null, category: "motivacion" },
  { id: "mot53", text: "La vida es un regalo, vívela así.", author: null, source: null, category: "motivacion" },
  { id: "mot54", text: "No hay fracaso, solo lecciones.", author: null, source: null, category: "motivacion" },
  { id: "mot55", text: "Tu luz brilla en la oscuridad.", author: null, source: null, category: "motivacion" },
  { id: "mot56", text: "La vida comienza donde termina la comodidad.", author: null, source: null, category: "motivacion" },
  { id: "mot57", text: "Eres un campeón en construcción.", author: null, source: null, category: "motivacion" },
  { id: "mot58", text: "La vida recompensa la acción.", author: null, source: null, category: "motivacion" },
  { id: "mot59", text: "Tu potencial no tiene límites.", author: null, source: null, category: "motivacion" },
  { id: "mot60", text: "Cada momento es una nueva oportunidad.", author: null, source: null, category: "motivacion" },
  { id: "mot61", text: "Eres digno de tus sueños.", author: null, source: null, category: "motivacion" },
  { id: "mot62", text: "La vida es ahora, no después.", author: null, source: null, category: "motivacion" },
  { id: "mot63", text: "Tu determinación puede mover montañas.", author: null, source: null, category: "motivacion" },
  { id: "mot64", text: "Eres inspiración para otros.", author: null, source: null, category: "motivacion" },
  { id: "mot65", text: "No existe el plan B, solo existe el plan A mejorado.", author: null, source: null, category: "motivacion" },
  { id: "mot66", text: "Tu éxito es inspiración para otros.", author: null, source: null, category: "motivacion" },
  { id: "mot67", text: "Eres más que tus dudas.", author: null, source: null, category: "motivacion" },
  { id: "mot68", text: "La grandeza nace de atreverte.", author: null, source: null, category: "motivacion" },
  { id: "mot69", text: "Tu visión es tu brújula.", author: null, source: null, category: "motivacion" },
  { id: "mot70", text: "Tu valentía puede cambiar el mundo.", author: null, source: null, category: "motivacion" },
  { id: "mot71", text: "Eres el héroe de tu propia historia.", author: null, source: null, category: "motivacion" },

  // ── Mentalidad & Enfoque (50) ────────────────────────────────────────────
  { id: "men1", text: "La mente es todo en el juego mental.", author: null, source: null, category: "mentalidad" },
  { id: "men2", text: "Tu enfoque determina tu realidad.", author: "Tony Robbins", source: null, category: "mentalidad" },
  { id: "men3", text: "Lo que la mente puede concebir, puede lograr.", author: "Napoleon Hill", source: null, category: "mentalidad" },
  { id: "men4", text: "La mentalidad ganadora es la clave del éxito.", author: null, source: null, category: "mentalidad" },
  { id: "men5", text: "Tu pensamiento es tu realidad.", author: "Wayne Dyer", source: null, category: "mentalidad" },
  { id: "men6", text: "La mente fuerte vence al cuerpo fuerte.", author: "Sun Tzu", source: null, category: "mentalidad" },
  { id: "men7", text: "Enfócate en lo que puedes controlar.", author: "Ryan Holiday", source: null, category: "mentalidad" },
  { id: "men8", text: "La mente es el campo de batalla.", author: null, source: null, category: "mentalidad" },
  { id: "men9", text: "Tu perspectiva es tu poder.", author: null, source: null, category: "mentalidad" },
  { id: "men10", text: "La disciplina mental es más difícil que la física.", author: null, source: null, category: "mentalidad" },
  { id: "men11", text: "Tu mentalidad define tu altitud.", author: null, source: null, category: "mentalidad" },
  { id: "men12", text: "El éxito comienza en la mente.", author: null, source: null, category: "mentalidad" },
  { id: "men13", text: "Tu mente es tu mejor aliado o tu peor enemigo.", author: null, source: null, category: "mentalidad" },
  { id: "men14", text: "La concentración es el poder.", author: null, source: null, category: "mentalidad" },
  { id: "men15", text: "Tu mentalidad es tu superpoder.", author: null, source: null, category: "mentalidad" },
  { id: "men16", text: "El enfoque es la disciplina de la mente.", author: null, source: null, category: "mentalidad" },
  { id: "men17", text: "Tu mente es tu arma más afilada.", author: null, source: null, category: "mentalidad" },
  { id: "men18", text: "La mentalidad es el 90% del juego.", author: null, source: null, category: "mentalidad" },
  { id: "men19", text: "Tu pensamiento positivo es tu mejor inversión.", author: null, source: null, category: "mentalidad" },
  { id: "men20", text: "La mente enfocada logra lo imposible.", author: null, source: null, category: "mentalidad" },
  { id: "men21", text: "Tu mentalidad es tu destino.", author: null, source: null, category: "mentalidad" },
  { id: "men22", text: "El éxito es una decisión mental.", author: null, source: null, category: "mentalidad" },
  { id: "men23", text: "Tu mente es tu creadora de realidad.", author: null, source: null, category: "mentalidad" },
  { id: "men24", text: "La mentalidad fuerte supera la adversidad.", author: null, source: null, category: "mentalidad" },
  { id: "men25", text: "Tu enfoque es tu superpoder.", author: null, source: null, category: "mentalidad" },
  { id: "men26", text: "La mente disciplinada es invencible.", author: null, source: null, category: "mentalidad" },
  { id: "men27", text: "Tu pensamiento es la semilla de tu éxito.", author: null, source: null, category: "mentalidad" },
  { id: "men28", text: "La mentalidad de campeón se cultiva.", author: null, source: null, category: "mentalidad" },
  { id: "men29", text: "Tu mente es tu mayor recurso.", author: null, source: null, category: "mentalidad" },
  { id: "men30", text: "El enfoque es la magia de la productividad.", author: null, source: null, category: "mentalidad" },
  { id: "men31", text: "Tu mentalidad determina tu elevación.", author: null, source: null, category: "mentalidad" },
  { id: "men32", text: "La mente que se concentra logra montañas.", author: null, source: null, category: "mentalidad" },
  { id: "men33", text: "Tu pensamiento crea tu experiencia.", author: null, source: null, category: "mentalidad" },
  { id: "men34", text: "La mentalidad es el constructor del destino.", author: null, source: null, category: "mentalidad" },
  { id: "men35", text: "Tu enfoque es tu brújula en la vida.", author: null, source: null, category: "mentalidad" },
  { id: "men36", text: "La mente fuerte es el cimiento del éxito.", author: null, source: null, category: "mentalidad" },
  { id: "men37", text: "Tu mentalidad es tu mayor fortaleza.", author: null, source: null, category: "mentalidad" },
  { id: "men38", text: "El enfoque es la disciplina del éxito.", author: null, source: null, category: "mentalidad" },
  { id: "men39", text: "Tu pensamiento es tu arquitecto de destino.", author: null, source: null, category: "mentalidad" },
  { id: "men40", text: "La mentalidad ganadora se construye diariamente.", author: null, source: null, category: "mentalidad" },
  { id: "men41", text: "Tu mente es tu mejor amiga cuando enfoca.", author: null, source: null, category: "mentalidad" },
  { id: "men42", text: "El enfoque es la clave de la maestría.", author: null, source: null, category: "mentalidad" },
  { id: "men43", text: "Tu mentalidad crea tu realidad.", author: null, source: null, category: "mentalidad" },
  { id: "men44", text: "La mente disciplinada logra lo extraordinario.", author: null, source: null, category: "mentalidad" },
  { id: "men45", text: "Tu pensamiento es tu punto de partida.", author: null, source: null, category: "mentalidad" },
  { id: "men46", text: "La mentalidad fuerte no tiene límites.", author: null, source: null, category: "mentalidad" },
  { id: "men47", text: "Tu enfoque es tu inversión más valiosa.", author: null, source: null, category: "mentalidad" },
  { id: "men48", text: "La mente enfocada es una máquina de logros.", author: null, source: null, category: "mentalidad" },
  { id: "men49", text: "Tu mentalidad determina tu altitud.", author: null, source: null, category: "mentalidad" },
  { id: "men50", text: "El enfoque es el puente hacia el éxito.", author: null, source: null, category: "mentalidad" },

  // ── Reflexión general (50) ───────────────────────────────────────────────
  { id: "ref1", text: "La vida es 10% lo que te sucede y 90% cómo reaccionas.", author: "Charles R. Swindoll", source: null, category: "reflexion" },
  { id: "ref2", text: "Vive como si fueras a morir mañana; aprende como si fueras a vivir para siempre.", author: "Mahatma Gandhi", source: null, category: "reflexion" },
  { id: "ref3", text: "El cambio es la única constante.", author: "Heráclito", source: null, category: "reflexion" },
  { id: "ref4", text: "La felicidad no es un destino, es un viaje.", author: null, source: null, category: "reflexion" },
  { id: "ref5", text: "El éxito es caminar de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill", source: null, category: "reflexion" },
  { id: "ref6", text: "La vida es lo que sucede mientras planeas el futuro.", author: "John Lennon", source: null, category: "reflexion" },
  { id: "ref7", text: "La muerte no es el opuesto de la vida, es el opuesto del nacimiento.", author: "Haruki Murakami", source: null, category: "reflexion" },
  { id: "ref8", text: "Cada día es una nueva oportunidad de cambiar tu vida.", author: "Ralph Marston", source: null, category: "reflexion" },
  { id: "ref9", text: "La vida te enseña si estás dispuesto a aprender.", author: null, source: null, category: "reflexion" },
  { id: "ref10", text: "El arrepentimiento es la carga más pesada de llevar.", author: null, source: null, category: "reflexion" },
  { id: "ref11", text: "La vida es simple, pero nosotros la complicamos.", author: "Confucio", source: null, category: "reflexion" },
  { id: "ref12", text: "El tiempo es tu recurso más valioso, gástalo sabiamente.", author: null, source: null, category: "reflexion" },
  { id: "ref13", text: "La vida no es sobre encontrar quién eres, es sobre crear quién eres.", author: "George Bernard Shaw", source: null, category: "reflexion" },
  { id: "ref14", text: "La juventud es el regalo de la naturaleza, la vejez es el regalo del arte.", author: "Oscar Wilde", source: null, category: "reflexion" },
  { id: "ref15", text: "La vida es una cuestión de prioridades.", author: null, source: null, category: "reflexion" },
  { id: "ref16", text: "Lo que no cambias, no mejora.", author: null, source: null, category: "reflexion" },
  { id: "ref17", text: "La vida es más dulce cuando no tienes expectativas.", author: null, source: null, category: "reflexion" },
  { id: "ref18", text: "El significado de la vida es encontrar tu propósito.", author: null, source: null, category: "reflexion" },
  { id: "ref19", text: "La vida es una aventura o no es nada.", author: "Helen Keller", source: null, category: "reflexion" },
  { id: "ref20", text: "La mejor vida es la que vives de acuerdo a tus valores.", author: null, source: null, category: "reflexion" },
  { id: "ref21", text: "La vida está hecha de momentos, no de años.", author: "Ralph Waldo Emerson", source: null, category: "reflexion" },
  { id: "ref22", text: "Cada día es una segunda oportunidad.", author: "Dennis the Menace", source: null, category: "reflexion" },
  { id: "ref23", text: "La vida es demasiado corta para las preocupaciones innecesarias.", author: null, source: null, category: "reflexion" },
  { id: "ref24", text: "El significado de la vida está en vivirla.", author: null, source: null, category: "reflexion" },
  { id: "ref25", text: "La vida es el juego más serio que existe.", author: null, source: null, category: "reflexion" },
  { id: "ref26", text: "Lo que no haces hoy te perseguirá mañana.", author: null, source: null, category: "reflexion" },
  { id: "ref27", text: "La vida es una mezcla de alegría y dolor.", author: null, source: null, category: "reflexion" },
  { id: "ref28", text: "La experiencia es el mejor profesor.", author: null, source: null, category: "reflexion" },
  { id: "ref29", text: "La vida no es sobre el destino, es sobre el viaje.", author: "Ralph Waldo Emerson", source: null, category: "reflexion" },
  { id: "ref30", text: "La verdadera riqueza es tener una vida plena.", author: null, source: null, category: "reflexion" },
  { id: "ref31", text: "La vida es una novela, no un cuento corto.", author: null, source: null, category: "reflexion" },
  { id: "ref32", text: "La vida es lo que haces cuando estás ocupado planeando otra cosa.", author: null, source: null, category: "reflexion" },
  { id: "ref33", text: "El tiempo no espera, aprovéchalo ahora.", author: null, source: null, category: "reflexion" },
  { id: "ref34", text: "La vida es una prueba, apruébala.", author: null, source: null, category: "reflexion" },
  { id: "ref35", text: "Cada momento es un regalo.", author: null, source: null, category: "reflexion" },
  { id: "ref36", text: "La vida es lo que decides que sea.", author: null, source: null, category: "reflexion" },
  { id: "ref37", text: "La verdadera vida comienza donde termina el miedo.", author: null, source: null, category: "reflexion" },
  { id: "ref38", text: "La vida es una oportunidad, no una garantía.", author: null, source: null, category: "reflexion" },
  { id: "ref39", text: "El arrepentimiento es más doloroso que el esfuerzo.", author: null, source: null, category: "reflexion" },
  { id: "ref40", text: "La vida es una bendición, vívela así.", author: null, source: null, category: "reflexion" },
  { id: "ref41", text: "La vida es un viaje, no una carrera.", author: null, source: null, category: "reflexion" },
  { id: "ref42", text: "La belleza de la vida está en sus incertidumbres.", author: null, source: null, category: "reflexion" },
  { id: "ref43", text: "La vida es demasiado corta para no ser feliz.", author: null, source: null, category: "reflexion" },
  { id: "ref44", text: "Cada momento es una oportunidad de redención.", author: null, source: null, category: "reflexion" },
  { id: "ref45", text: "La vida es lo que haces con ella.", author: null, source: null, category: "reflexion" },
  { id: "ref46", text: "La felicidad viene de vivir con propósito.", author: null, source: null, category: "reflexion" },
  { id: "ref47", text: "La vida es un espejo de tus acciones.", author: null, source: null, category: "reflexion" },
  { id: "ref48", text: "La verdadera vida está en el ahora.", author: null, source: null, category: "reflexion" },
  { id: "ref49", text: "La vida es tu responsabilidad.", author: null, source: null, category: "reflexion" },
  { id: "ref50", text: "La vida es una obra maestra en progreso.", author: null, source: null, category: "reflexion" },

  // ── Estoicismo (51) ──────────────────────────────────────────────────────
  { id: "est1", text: "No podemos controlar lo que sucede, solo cómo reaccionamos.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est2", text: "La virtud es la única cosa verdaderamente valiosa.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est3", text: "Eres dueño de tus acciones, no de sus resultados.", author: null, source: "Bhagavad Gita", category: "estoicismo" },
  { id: "est4", text: "La aceptación es el primer paso hacia la paz.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est5", text: "Todo lo que sucede es una oportunidad para practicar la virtud.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est6", text: "El destino guía al hombre dispuesto y arrastra al renuente.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est7", text: "La muerte no es un mal, solo es inevitable.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est8", text: "No temas lo que no puedes controlar.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est9", text: "La preocupación es un desperdicio de tu poder mental.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est10", text: "Todo lo que es tuyo puede ser arrebatado, prepárate.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est11", text: "La adversidad forja el carácter.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est12", text: "Tu poder está en tu reacción, no en el evento.", author: "Ryan Holiday", source: null, category: "estoicismo" },
  { id: "est13", text: "El sufrimiento es opcional, el dolor es inevitable.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est14", text: "La rabia es un desperdicio de tu energía.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est15", text: "Aceptar lo que no puedes cambiar es libertad.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est16", text: "El verdadero poder es la autodeterminación.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est17", text: "La vida es un acto de voluntad, no de destino.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est18", text: "El miedo es la falta de dominio propio.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est19", text: "Todo obstáculo es una oportunidad de ser mejor.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est20", text: "La sabiduría es conocer qué está en tu control.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est21", text: "No juzgues el valor de una vida por su duración.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est22", text: "La persistencia es la virtud del fuerte.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est23", text: "Tu mente es tu castillo, defiéndela.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est24", text: "Lo que importa es cómo reaccionas, no lo que sucede.", author: "Ryan Holiday", source: null, category: "estoicismo" },
  { id: "est25", text: "La libertad es elegir tu reacción.", author: "Victor Frankl", source: null, category: "estoicismo" },
  { id: "est26", text: "El dolor es pasajero, el crecimiento es permanente.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est27", text: "La simpleza es la verdadera sofisticación.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est28", text: "El tiempo es tu recurso más limitado, no lo desperdicies.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est29", text: "La disciplina es la libertad.", author: "Jocko Willink", source: null, category: "estoicismo" },
  { id: "est30", text: "Todo sucede por una razón, encuentra el propósito.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est31", text: "No tengas miedo del cambio, es la única constante.", author: "Heráclito", source: null, category: "estoicismo" },
  { id: "est32", text: "El verdadero éxito es la paz interior.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est33", text: "Tu reputación no es asunto tuyo.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est34", text: "La muerte es el fin, no el fracaso.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est35", text: "El verdadero enemigo está dentro de ti.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est36", text: "La aceptación es una fortaleza, no una debilidad.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est37", text: "La vida es una serie de pruebas, apruébalas.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est38", text: "Tu control termina donde comienza el control de otros.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est39", text: "La paciencia es la manifestación de la sabiduría.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est40", text: "El verdadero lujo es la libertad mental.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est41", text: "La ira es la reacción del débil.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est42", text: "Tu carácter es tu destino.", author: "Heráclito", source: null, category: "estoicismo" },
  { id: "est43", text: "La virtud es su propia recompensa.", author: "Platón", source: null, category: "estoicismo" },
  { id: "est44", text: "Lo pasado no importa, solo el ahora.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est45", text: "La adversidad es el mejor profesor.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est46", text: "Tu responsabilidad es con tus acciones, no sus resultados.", author: "Epicteto", source: null, category: "estoicismo" },
  { id: "est47", text: "La tranquilidad es el objetivo final.", author: "Séneca", source: null, category: "estoicismo" },
  { id: "est48", text: "El verdadero daño es cuando dañas tu propio carácter.", author: "Marco Aurelio", source: null, category: "estoicismo" },
  { id: "est49", text: "La filosofía es la práctica de la muerte.", author: "Platón", source: null, category: "estoicismo" },
  { id: "est50", text: "Tu verdadero enemigo es tu propia ignorancia.", author: "Sócrates", source: null, category: "estoicismo" },
  { id: "est51", text: "La vida es un regalo, úsalo sabiamente.", author: "Marco Aurelio", source: null, category: "estoicismo" },

  // ── Filosofía clásica (50) ───────────────────────────────────────────────
  { id: "filo1", text: "La virtud es el conocimiento.", author: "Sócrates", source: null, category: "filosofia" },
  { id: "filo2", text: "El hombre es la medida de todas las cosas.", author: "Protágoras", source: null, category: "filosofia" },
  { id: "filo3", text: "La pregunta es más importante que la respuesta.", author: "Sócrates", source: null, category: "filosofia" },
  { id: "filo4", text: "Conócete a ti mismo.", author: "Sócrates", source: null, category: "filosofia" },
  { id: "filo5", text: "La verdadera riqueza es la sabiduría.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo6", text: "La justicia es el bien supremo.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo7", text: "Todo fluye, nada permanece.", author: "Heráclito", source: null, category: "filosofia" },
  { id: "filo8", text: "La razón es la guía del hombre.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo9", text: "El ser es, el no-ser no es.", author: "Parménides", source: null, category: "filosofia" },
  { id: "filo10", text: "La virtud está en el término medio.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo11", text: "El hombre es un animal político.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo12", text: "La eudaimonía es el objetivo de la vida.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo13", text: "La ignorancia es la raíz del mal.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo14", text: "La amistad es el corazón de la felicidad.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo15", text: "El buen vivir es el arte de la vida.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo16", text: "La justicia requiere virtud.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo17", text: "La belleza es verdad, la verdad es belleza.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo18", text: "El yo es la base del conocimiento.", author: "Descartes", source: null, category: "filosofia" },
  { id: "filo19", text: "La razón sin pasión es fría.", author: "Hume", source: null, category: "filosofia" },
  { id: "filo20", text: "La libertad es la esencia del ser.", author: "Sartre", source: null, category: "filosofia" },
  { id: "filo21", text: "La existencia precede a la esencia.", author: "Sartre", source: null, category: "filosofia" },
  { id: "filo22", text: "La verdad es constructiva, no destructiva.", author: "Wittgenstein", source: null, category: "filosofia" },
  { id: "filo23", text: "El significado está en el lenguaje.", author: "Wittgenstein", source: null, category: "filosofia" },
  { id: "filo24", text: "La razón práctica es más importante que la teórica.", author: "Kant", source: null, category: "filosofia" },
  { id: "filo25", text: "El deber es la base de la moralidad.", author: "Kant", source: null, category: "filosofia" },
  { id: "filo26", text: "El hombre es fin en sí mismo.", author: "Kant", source: null, category: "filosofia" },
  { id: "filo27", text: "La crítica es el camino hacia la verdad.", author: "Kant", source: null, category: "filosofia" },
  { id: "filo28", text: "La libertad es un derecho inalienable.", author: "Locke", source: null, category: "filosofia" },
  { id: "filo29", text: "El poder absoluto corrompe absolutamente.", author: "Lord Acton", source: null, category: "filosofia" },
  { id: "filo30", text: "La naturaleza humana es esencialmente social.", author: "Hobbes", source: null, category: "filosofia" },
  { id: "filo31", text: "La verdadera democracia nace del consentimiento.", author: "Rousseau", source: null, category: "filosofia" },
  { id: "filo32", text: "La educación es la clave de la libertad.", author: "Kant", source: null, category: "filosofia" },
  { id: "filo33", text: "La razón es universal.", author: "Kant", source: null, category: "filosofia" },
  { id: "filo34", text: "El hombre es lo que come.", author: "Feuerbach", source: null, category: "filosofia" },
  { id: "filo35", text: "La historia es el juez final.", author: "Hegel", source: null, category: "filosofia" },
  { id: "filo36", text: "La dialéctica es el método de la verdad.", author: "Hegel", source: null, category: "filosofia" },
  { id: "filo37", text: "La materia es la base de la conciencia.", author: "Marx", source: null, category: "filosofia" },
  { id: "filo38", text: "El trabajo es la esencia de la humanidad.", author: "Marx", source: null, category: "filosofia" },
  { id: "filo39", text: "La sociedad es más importante que el individuo.", author: "Durkheim", source: null, category: "filosofia" },
  { id: "filo40", text: "El conocimiento es poder.", author: "Francis Bacon", source: null, category: "filosofia" },
  { id: "filo41", text: "La experiencia es el mejor maestro.", author: null, source: "Empirismo", category: "filosofia" },
  { id: "filo42", text: "La lógica es el arte del razonamiento.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo43", text: "El bien común es el objetivo de la política.", author: "Cicerón", source: null, category: "filosofia" },
  { id: "filo44", text: "La vida examinada vale la pena vivir.", author: "Sócrates", source: null, category: "filosofia" },
  { id: "filo45", text: "El valor es la base de la vida virtuosa.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo46", text: "La sabiduría viene de la experiencia.", author: "Aristóteles", source: null, category: "filosofia" },
  { id: "filo47", text: "La verdad no necesita defensa.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo48", text: "El alma es inmortal.", author: "Platón", source: null, category: "filosofia" },
  { id: "filo49", text: "La justicia es dar a cada uno lo suyo.", author: "Cicerón", source: null, category: "filosofia" },
  { id: "filo50", text: "La felicidad es la concordia del alma.", author: "Sócrates", source: null, category: "filosofia" },

  // ── Fisicoculturistas (40) ───────────────────────────────────────────────
  { id: "fis1", text: "El único lugar donde el éxito viene antes del trabajo es en el diccionario.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis2", text: "Lo importante es tener una visión clara y confiar en ella.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis3", text: "El músculo que no usas, lo pierdes.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis4", text: "El hierro no miente.", author: "Henry Rollins", source: null, category: "fisicoculturistas" },
  { id: "fis5", text: "El entrenamiento es una cuestión de consistencia y disciplina.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis6", text: "Tu cuerpo puede aguantar casi cualquier castigo.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis7", text: "La visualización es la primera clave del éxito en el fisicoculturismo.", author: "Joe Weider", source: null, category: "fisicoculturistas" },
  { id: "fis8", text: "El verdadero campeón no teme el dolor.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis9", text: "El fisicoculturismo es el arte de transformar el cuerpo.", author: "Reg Park", source: null, category: "fisicoculturistas" },
  { id: "fis10", text: "No hay fórmula secreta, solo trabajo duro.", author: "Dorian Yates", source: null, category: "fisicoculturistas" },
  { id: "fis11", text: "La mente es el músculo más importante.", author: "Kai Greene", source: null, category: "fisicoculturistas" },
  { id: "fis12", text: "El éxito es la suma de pequeños esfuerzos constantes.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis13", text: "Entrena como si nadie te estuviera viendo.", author: "Kai Greene", source: null, category: "fisicoculturistas" },
  { id: "fis14", text: "La disciplina es hacer lo que necesitas sin que te apetezca.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis15", text: "El fisicoculturismo no es un deporte, es un estilo de vida.", author: "Jay Cutler", source: null, category: "fisicoculturistas" },
  { id: "fis16", text: "La consistencia es lo que separa a los ganadores de los perdedores.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis17", text: "Tu cuerpo es tu templo.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis18", text: "El dolor no es excusa, es motivación.", author: "Dorian Yates", source: null, category: "fisicoculturistas" },
  { id: "fis19", text: "La dedicación es lo que te hace un campeón.", author: "Ronnie Coleman", source: null, category: "fisicoculturistas" },
  { id: "fis20", text: "No te quejes del hambre, te entrenan tus músculos.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis21", text: "El verdadero trabajo comienza cuando tu cuerpo grita que pare.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis22", text: "La pasión es lo que te mantiene entrenando cuando otros descansan.", author: "Kai Greene", source: null, category: "fisicoculturistas" },
  { id: "fis23", text: "El músculo crece cuando duermes, entrena cuando estés despierto.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis24", text: "La visualización es tan importante como el entrenamiento.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis25", text: "No hay atajos para la excelencia.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis26", text: "El fisicoculturismo enseña disciplina y sacrificio.", author: "Jay Cutler", source: null, category: "fisicoculturistas" },
  { id: "fis27", text: "Cada serie cuenta, cada repetición importa.", author: "Dorian Yates", source: null, category: "fisicoculturistas" },
  { id: "fis28", text: "La dedicación es más importante que el talento.", author: "Ronnie Coleman", source: null, category: "fisicoculturistas" },
  { id: "fis29", text: "Tu cuerpo es lo que comes.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis30", text: "El entrenamiento sin nutrición es un fracaso.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis31", text: "La mentalidad de ganador es necesaria para ganar.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis32", text: "No hay límite en lo que puedes lograr si crees.", author: "Kai Greene", source: null, category: "fisicoculturistas" },
  { id: "fis33", text: "La consistencia es el secreto de los campeones.", author: "Ronnie Coleman", source: null, category: "fisicoculturistas" },
  { id: "fis34", text: "El dolor es temporal, el orgullo es para siempre.", author: "Arnold Schwarzenegger", source: null, category: "fisicoculturistas" },
  { id: "fis35", text: "El verdadero fisicoculturismo es mental.", author: "Kai Greene", source: null, category: "fisicoculturistas" },
  { id: "fis36", text: "Cada día en el gimnasio es una batalla.", author: "Lee Haney", source: null, category: "fisicoculturistas" },
  { id: "fis37", text: "La disciplina es tu mejor amiga.", author: "Jay Cutler", source: null, category: "fisicoculturistas" },
  { id: "fis38", text: "El éxito no viene del talento, viene del esfuerzo.", author: "Dorian Yates", source: null, category: "fisicoculturistas" },
  { id: "fis39", text: "La pasión es lo que te hace diferente.", author: "Kai Greene", source: null, category: "fisicoculturistas" },
  { id: "fis40", text: "Tu cuerpo es el lienzo, el entrenamiento es el arte.", author: null, source: null, category: "fisicoculturistas" },

  // ── Versículos bíblicos (40) ─────────────────────────────────────────────
  { id: "bib1", text: "Todo lo puedo en Cristo que me fortalece.", author: null, source: "Filipenses 4:13", category: "biblia" },
  { id: "bib2", text: "Porque somos hechura de Dios, creados en Cristo Jesús para buenas obras.", author: null, source: "Efesios 2:10", category: "biblia" },
  { id: "bib3", text: "Aunque ande en valle de sombra de muerte, no temeré mal alguno.", author: null, source: "Salmo 23:4", category: "biblia" },
  { id: "bib4", text: "Confía en el Señor de todo tu corazón y no en tu propia inteligencia.", author: null, source: "Proverbios 3:5", category: "biblia" },
  { id: "bib5", text: "Con Dios todo es posible.", author: null, source: "Mateo 19:26", category: "biblia" },
  { id: "bib6", text: "Dios no nos ha dado espíritu de cobardía, sino de poder, de amor y de dominio propio.", author: null, source: "2 Timoteo 1:7", category: "biblia" },
  { id: "bib7", text: "Mis mandamientos son para tu bien y el de tu familia.", author: null, source: "Deuteronomio 6:6", category: "biblia" },
  { id: "bib8", text: "El que persevera hasta el final será salvo.", author: null, source: "Mateo 24:13", category: "biblia" },
  { id: "bib9", text: "En la multitud de consejeros hay seguridad.", author: null, source: "Proverbios 11:14", category: "biblia" },
  { id: "bib10", text: "Mañana no sé lo que traerá, confío en Dios.", author: null, source: "Proverbios 27:1", category: "biblia" },
  { id: "bib11", text: "Por eso nos es necesario tener una fe más firme.", author: null, source: "2 Pedro 1:10", category: "biblia" },
  { id: "bib12", text: "No os conforméis a este siglo, sino transformaos.", author: null, source: "Romanos 12:2", category: "biblia" },
  { id: "bib13", text: "Porque por gracia sois salvos, por medio de la fe.", author: null, source: "Efesios 2:8", category: "biblia" },
  { id: "bib14", text: "Siendo pues libre de la culpa, estamos en paz con Dios.", author: null, source: "Romanos 5:1", category: "biblia" },
  { id: "bib15", text: "Porque conoceréis la verdad, y la verdad os hará libres.", author: null, source: "Juan 8:32", category: "biblia" },
  { id: "bib16", text: "Por tanto, mi Dios suplirá todo lo que os falta.", author: null, source: "Filipenses 4:19", category: "biblia" },
  { id: "bib17", text: "Buscad primero el reino de Dios y su justicia.", author: null, source: "Mateo 6:33", category: "biblia" },
  { id: "bib18", text: "Nada hay imposible para Dios.", author: null, source: "Lucas 1:37", category: "biblia" },
  { id: "bib19", text: "Encomienda tu camino al Señor y Él actuará.", author: null, source: "Salmo 37:5", category: "biblia" },
  { id: "bib20", text: "Ahora, pues, no hay condenación para los que están en Cristo Jesús.", author: null, source: "Romanos 8:1", category: "biblia" },
  { id: "bib21", text: "La fe sin obras está muerta.", author: null, source: "Santiago 2:26", category: "biblia" },
  { id: "bib22", text: "No temas, porque yo estoy contigo.", author: null, source: "Isaías 41:10", category: "biblia" },
  { id: "bib23", text: "Corre la carrera que te propone, mirando a Jesús.", author: null, source: "Hebreos 12:1-2", category: "biblia" },
  { id: "bib24", text: "Porque os he dicho estas cosas, para que en mí tengáis paz.", author: null, source: "Juan 16:33", category: "biblia" },
  { id: "bib25", text: "Pero Jesús les miró y dijo: Para los hombres esto es imposible, pero para Dios todo es posible.", author: null, source: "Mateo 19:26", category: "biblia" },
  { id: "bib26", text: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.", author: null, source: "Romanos 8:28", category: "biblia" },
  { id: "bib27", text: "Vosotros sois la luz del mundo; no puede ser oculta la ciudad que está sobre un monte.", author: null, source: "Mateo 5:14", category: "biblia" },
  { id: "bib28", text: "Porque Dios no es un Dios de confusión, sino de paz.", author: null, source: "1 Corintios 14:33", category: "biblia" },
  { id: "bib29", text: "Bienaventurados los que oyen la palabra de Dios y la guardan.", author: null, source: "Lucas 11:28", category: "biblia" },
  { id: "bib30", text: "Porque mayor es el que está en vosotros, que el que está en el mundo.", author: null, source: "1 Juan 4:4", category: "biblia" },
  { id: "bib31", text: "He venido para que tengan vida y vida en abundancia.", author: null, source: "Juan 10:10", category: "biblia" },
  { id: "bib32", text: "Pero en todas estas cosas somos más que vencedores por medio de aquel que nos amó.", author: null, source: "Romanos 8:37", category: "biblia" },
  { id: "bib33", text: "Porque la palabra de Dios es viva y eficaz.", author: null, source: "Hebreos 4:12", category: "biblia" },
  { id: "bib34", text: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", author: null, source: "Salmo 46:1", category: "biblia" },
  { id: "bib35", text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", author: null, source: "Mateo 11:28", category: "biblia" },
  { id: "bib36", text: "Porque somos embajadores de Cristo, como si Dios rogase por medio de nosotros.", author: null, source: "2 Corintios 5:20", category: "biblia" },
  { id: "bib37", text: "Si Dios es por nosotros, ¿quién contra nosotros?", author: null, source: "Romanos 8:31", category: "biblia" },
  { id: "bib38", text: "Porque el que cree en mí, aunque esté muerto, vivirá.", author: null, source: "Juan 11:25", category: "biblia" },
  { id: "bib39", text: "La palabra de Dios no volverá a mí sin cumplirse.", author: null, source: "Isaías 55:11", category: "biblia" },
  { id: "bib40", text: "Porque somos hijos de Dios, somos también herederos de Dios.", author: null, source: "Romanos 8:16-17", category: "biblia" },

  // ── Budismo (25) ─────────────────────────────────────────────────────────
  { id: "bud1", text: "El sufrimiento surge del apego y la ignorancia.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud2", text: "El camino del medio es la verdad.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud3", text: "Sé una lámpara para ti mismo.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud4", text: "La mente es todo. Lo que piensas, lo que te conviertes.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud5", text: "Quien conquista a sí mismo es más grande que quien conquista mil hombres en batalla.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud6", text: "La paz viene del interior. No busques la paz en el exterior.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud7", text: "La aceptación es el camino hacia la libertad.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud8", text: "El presente es el único momento que existe.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud9", text: "La compasión es la verdadera religión.", author: "Dalai Lama", source: null, category: "budismo" },
  { id: "bud10", text: "El cambio es la naturaleza de todas las cosas.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud11", text: "La iluminación es el despertar de la verdad.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud12", text: "La meditación es el camino hacia la verdad.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud13", text: "El verdadero poder es el control de uno mismo.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud14", text: "La compasión hacia todos los seres es la virtud suprema.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud15", text: "El desapego es la libertad.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud16", text: "La mindfulness es la puerta a la iluminación.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud17", text: "Quien no lucha consigo mismo, lucha con el mundo.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud18", text: "La verdadera riqueza es la satisfacción.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud19", text: "La gratitud es el camino hacia la paz.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud20", text: "El perdón es la máxima forma de compasión.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud21", text: "La bondad es el verdadero poder.", author: "Dalai Lama", source: null, category: "budismo" },
  { id: "bud22", text: "La paciencia es la virtud del fuerte.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud23", text: "La vida es efímera, aprecia cada momento.", author: "Buddha", source: null, category: "budismo" },
  { id: "bud24", text: "La verdadera felicidad viene del interior.", author: "Dalai Lama", source: null, category: "budismo" },
  { id: "bud25", text: "El camino de la iluminación es el camino de la compasión.", author: "Buddha", source: null, category: "budismo" },

  // ── Hinduismo (20) ───────────────────────────────────────────────────────
  { id: "hin1", text: "Tu verdadero yo es eterno e inmortal.", author: null, source: "Bhagavad Gita", category: "hinduismo" },
  { id: "hin2", text: "Eres el Brahman, la consciencia suprema.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin3", text: "El dharma es tu verdadero propósito en la vida.", author: null, source: "Bhagavad Gita", category: "hinduismo" },
  { id: "hin4", text: "El karma es la ley de causa y efecto.", author: null, source: null, category: "hinduismo" },
  { id: "hin5", text: "La acción desinteresada es el camino hacia la libertad.", author: null, source: "Bhagavad Gita", category: "hinduismo" },
  { id: "hin6", text: "Todo lo que ves es divino.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin7", text: "La ignorancia es la raíz del sufrimiento.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin8", text: "La realización del yo es el objetivo supremo.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin9", text: "Tú eres lo que piensas habitualmente.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin10", text: "La vida es un viaje del alma hacia la perfección.", author: null, source: null, category: "hinduismo" },
  { id: "hin11", text: "La verdadera victoria es la victoria sobre uno mismo.", author: null, source: "Bhagavad Gita", category: "hinduismo" },
  { id: "hin12", text: "La compasión es el reflejo del divino.", author: null, source: null, category: "hinduismo" },
  { id: "hin13", text: "El alma es eterna, el cuerpo es temporal.", author: null, source: "Bhagavad Gita", category: "hinduismo" },
  { id: "hin14", text: "La meditación es el puente hacia lo divino.", author: null, source: null, category: "hinduismo" },
  { id: "hin15", text: "Tu verdadera naturaleza es ser, consciencia, bienaventuranza.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin16", text: "La realidad última es una sola, sin dualidad.", author: null, source: "Upanishads", category: "hinduismo" },
  { id: "hin17", text: "Eres el espectador del drama de la vida.", author: null, source: null, category: "hinduismo" },
  { id: "hin18", text: "La fe es el fundamento de la libertad espiritual.", author: null, source: "Bhagavad Gita", category: "hinduismo" },
  { id: "hin19", text: "La vida es un juego divino.", author: null, source: null, category: "hinduismo" },
  { id: "hin20", text: "El verdadero conocimiento es el conocimiento del yo divino.", author: null, source: "Upanishads", category: "hinduismo" },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Filtra frases por categorías activas.
 * Si categories está vacío, devuelve todas.
 */
export function filterQuotes(
  activeCategories: QuoteCategory[],
): Quote[] {
  if (activeCategories.length === 0) return QUOTES
  return QUOTES.filter((q) => activeCategories.includes(q.category))
}

/**
 * Elige una frase aleatoria evitando las recientes.
 * @param pool     frases disponibles
 * @param seenIds  IDs vistos recientemente (últimos N)
 */
export function pickQuote(pool: Quote[], seenIds: string[]): Quote {
  if (pool.length === 0) return QUOTES[0]

  // Preferir frases no vistas; si todas se han visto, usar todas
  const fresh = pool.filter((q) => !seenIds.includes(q.id))
  const candidates = fresh.length > 0 ? fresh : pool

  // Rotación por categoría: evitar misma categoría dos veces seguidas
  const lastId = seenIds[seenIds.length - 1]
  const lastQuote = pool.find((q) => q.id === lastId)
  const diffCat = lastQuote
    ? candidates.filter((q) => q.category !== lastQuote.category)
    : candidates
  const final = diffCat.length > 0 ? diffCat : candidates

  return final[Math.floor(Math.random() * final.length)]
}

/** Máximo de IDs recientes a recordar. */
export const SEEN_HISTORY_SIZE = 15
